"""
C4REQBER: 153 Metaprograms Library - Core MP data definitions
"""
from __future__ import annotations

from src.metamodels.mp.core import Metaprogram, MPDimension


CORE_METAPROGRAMS = [
    # THINKING
    Metaprogram(
        "MP-01",
        "Toward/Away",
        "К/От",
        MPDimension.THINKING,
        "toward goals",
        "away from problems",
        "Direction of motivation and attention",
        "Focus on achieving positive outcomes OR avoiding negative ones.",
    ),
    Metaprogram(
        "MP-02",
        "Options/Procedures",
        "Варианты/Процедуры",
        MPDimension.THINKING,
        "explore options",
        "follow procedures",
        "Preference for creativity vs adherence to established methods",
        "Generate alternatives OR follow proven steps.",
    ),
    Metaprogram(
        "MP-03",
        "Global/Detail",
        "Глобал/Деталист",
        MPDimension.THINKING,
        "global/big picture",
        "specific details",
        "Information granularity preference",
        "See the whole system OR focus on fine details.",
    ),
    Metaprogram(
        "MP-04",
        "Match/Mismatch",
        "Совпадение/Расхождение",
        MPDimension.THINKING,
        "find similarities",
        "find differences",
        "Comparison strategy",
        "Focus on what matches OR what diverges.",
    ),
    Metaprogram(
        "MP-05",
        "Rational/Intuitive",
        "Рационал/Интуит",
        MPDimension.THINKING,
        "logical analysis",
        "gut feeling",
        "Decision-making style",
        "Analyze systematically OR trust intuition.",
    ),
    # FEELING
    Metaprogram(
        "MP-06",
        "Optimistic/Pessimistic",
        "Оптимист/Пессимист",
        MPDimension.FEELING,
        "expect success",
        "expect problems",
        "Emotional forecasting bias",
        "Anticipate positive outcomes OR prepare for failures.",
    ),
    Metaprogram(
        "MP-07",
        "Internal/External",
        "Внутренний/Внешний",
        MPDimension.FEELING,
        "self-referenced",
        "other-referenced",
        "Source of validation",
        "Trust own judgment OR seek external validation.",
    ),
    Metaprogram(
        "MP-08",
        "Proactive/Reactive",
        "Проактив/Реактив",
        MPDimension.FEELING,
        "initiate action",
        "respond to events",
        "Initiation pattern",
        "Start things OR respond to triggers.",
    ),
    # DOING
    Metaprogram(
        "MP-09",
        "Independent/Cooperative",
        "Независимый/Кооперативный",
        MPDimension.DOING,
        "work alone",
        "work with others",
        "Collaboration preference",
        "Solve independently OR collaborate.",
    ),
    Metaprogram(
        "MP-10",
        "Fast/Slow",
        "Быстрый/Медленный",
        MPDimension.DOING,
        "quick decisions",
        "deliberate pace",
        "Processing speed",
        "Move fast OR take time to reflect.",
    ),
    Metaprogram(
        "MP-11",
        "Aggressive/Defensive",
        "Агрессивный/Оборонительный",
        MPDimension.DOING,
        "attack problems",
        "protect position",
        "Conflict strategy",
        "Aggressively pursue OR cautiously defend.",
    ),
    # RELATING
    Metaprogram(
        "MP-12",
        "Similar/Different",
        "Похожий/Отличный",
        MPDimension.RELATING,
        "find common ground",
        "assert uniqueness",
        "Social comparison",
        "Emphasize similarities OR differences.",
    ),
    Metaprogram(
        "MP-13",
        "Leading/Following",
        "Лидер/Последователь",
        MPDimension.RELATING,
        "take charge",
        "support others",
        "Social role preference",
        "Lead the group OR follow and support.",
    ),
    # PERCEIVING
    Metaprogram(
        id="MP-14",
        name="Visual/Auditory/Kinesthetic",
        name_ru="Визуал/Аудиал/Кинестетик",
        dimension=MPDimension.PERCEIVING,
        pole_a="see patterns",
        pole_b="hear relationships",
        description="Sensory channel preference (visual/auditory/kinesthetic)",
        agent_prompt_suffix="Process information visually, auditorily, or kinesthetically.",
    ),
    Metaprogram(
        "MP-15",
        "Abstract/Concrete",
        "Абстрактный/Конкретный",
        MPDimension.PERCEIVING,
        "theoretical",
        "practical",
        "Abstraction level",
        "Work with concepts OR concrete examples.",
    ),
    # TIME
    Metaprogram(
        id="MP-16",
        name="Past/Present/Future",
        name_ru="Прошлое/Настоящее/Будущее",
        dimension=MPDimension.TIME,
        pole_a="learn from history",
        pole_b="focus on now",
        description="Temporal focus (past/present/future)",
        agent_prompt_suffix="Draw from past, act in present, or plan for future.",
    ),
    Metaprogram(
        "MP-17",
        "Short-term/Long-term",
        "Краткосрочный/Долгосрочный",
        MPDimension.TIME,
        "immediate results",
        "delayed gratification",
        "Time horizon",
        "Optimize for now OR invest in future.",
    ),
    # CHUNKING
    Metaprogram(
        "MP-18",
        "General/Specific",
        "Общий/Частный",
        MPDimension.CHUNKING,
        "broad categories",
        "fine distinctions",
        "Information chunk size",
        "Group broadly OR differentiate finely.",
    ),
    Metaprogram(
        "MP-19",
        "Deep/Wide",
        "Глубокий/Широкий",
        MPDimension.CHUNKING,
        "deep dive",
        "broad survey",
        "Exploration strategy",
        "Explore deeply OR scan widely.",
    ),
    # DIRECTION
    Metaprogram(
        "MP-20",
        "Goal/Process",
        "Цель/Процесс",
        MPDimension.DIRECTION,
        "outcome-focused",
        "journey-focused",
        "Motivation direction",
        "Focus on destination OR enjoy the path.",
    ),
    Metaprogram(
        "MP-21",
        "Growth/Protection",
        "Рост/Защита",
        MPDimension.DIRECTION,
        "expand possibilities",
        "maintain safety",
        "Risk orientation",
        "Seek growth OR preserve stability.",
    ),
    # REASON
    Metaprogram(
        id="MP-22",
        name="Possibility/Necessity",
        name_ru="Возможность/Необходимость",
        dimension=MPDimension.REASON,
        pole_a="what's possible",
        pole_b="what's required",
        description="Decision basis (possibility/necessity)",
        agent_prompt_suffix="Explore options OR meet obligations.",
    ),
    Metaprogram(
        "MP-23",
        "Evidence/Tradition",
        "Доказательство/Традиция",
        MPDimension.REASON,
        "data-driven",
        "established wisdom",
        "Knowledge source",
        "Trust evidence OR tradition.",
    ),
]
