"""
TURBO-CDI: Export Module
Export discoveries to various formats (PDF, Markdown, LaTeX, HTML)
"""

import json
from datetime import datetime
from typing import List, Optional, Dict, Any
from pathlib import Path


class ExportManager:
    """
    Export research results to multiple formats.
    """

    def __init__(self, output_dir: Optional[str] = None):
        if output_dir is None:
            output_dir = Path.home() / "TURBO-CDI" / "exports"

        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def export_discovery_markdown(
        self, discovery: Dict[str, Any], filename: Optional[str] = None
    ) -> str:
        """Export discovery as Markdown."""
        if filename is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"discovery_{timestamp}.md"

        filepath = self.output_dir / filename

        content = f"""# Research Discovery

**Generated:** {discovery.get("created_at", datetime.now().isoformat())}  
**Domain:** {discovery.get("domain", "general")}  
**Confidence:** {discovery.get("confidence", 0.0):.2f}

---

## Problem Statement

{discovery.get("problem", "N/A")}

## Physical Contradiction

{discovery.get("contradiction", "N/A")}

## Generated Hypothesis

{discovery.get("hypothesis", "N/A")}

## C4 Navigation Path

```
{" → ".join(discovery.get("c4_path", []))}
```

**Steps taken:** {len(discovery.get("c4_path", []))}/6

## Falsifiability Criteria

"""

        for i, criterion in enumerate(discovery.get("falsifiability_criteria", []), 1):
            content += f"{i}. {criterion}\n"

        content += f"""

---

*Generated by TURBO-CDI v3.0*
"""

        with open(filepath, "w") as f:
            f.write(content)

        return str(filepath)

    def export_project_report(
        self,
        project: Dict[str, Any],
        discoveries: List[Dict],
        tasks: List[Dict],
        filename: Optional[str] = None,
    ) -> str:
        """Export full project report."""
        if filename is None:
            filename = f"project_{project.get('name', 'report').replace(' ', '_')}.md"

        filepath = self.output_dir / filename

        content = f"""# Research Project Report

## {project.get("name", "Untitled")}

**Status:** {project.get("status", "active")}  
**Domain:** {project.get("domain", "general")}  
**Created:** {project.get("created_at", "N/A")}

### Description

{project.get("description", "No description")}

### Objectives

"""

        for obj in project.get("objectives", []):
            content += f"- {obj}\n"

        content += f"""

### Hypotheses Generated ({len(discoveries)})

"""

        for i, disc in enumerate(discoveries, 1):
            content += f"#### {i}. {disc.get('hypothesis', 'N/A')[:100]}...\n\n"
            content += f"- **Confidence:** {disc.get('confidence', 0):.2f}\n"
            content += f"- **Status:** {disc.get('status', 'pending')}\n\n"

        content += f"""

### Tasks ({len(tasks)})

| Status | Count |
|--------|-------|
"""

        status_counts = {}
        for task in tasks:
            status = task.get("status", "unknown")
            status_counts[status] = status_counts.get(status, 0) + 1

        for status, count in sorted(status_counts.items()):
            content += f"| {status} | {count} |\n"

        content += f"""

---

*Report generated by TURBO-CDI v3.0*
"""

        with open(filepath, "w") as f:
            f.write(content)

        return str(filepath)

    def export_bibliography_latex(
        self, references: List[Dict], filename: str = "references.bib"
    ) -> str:
        """Export bibliography as LaTeX/BibTeX."""
        filepath = self.output_dir / filename

        with open(filepath, "w") as f:
            f.write("% Bibliography generated by TURBO-CDI\n\n")

            for ref in references:
                f.write(self._to_bibtex(ref))
                f.write("\n\n")

        return str(filepath)

    def _to_bibtex(self, ref: Dict) -> str:
        """Convert reference to BibTeX."""
        lines = [
            f"@{ref.get('entry_type', 'article')}{{{ref.get('cite_key', 'unknown')},"
        ]
        lines.append(f"  title = {{{ref.get('title', '')}}},")

        authors = ref.get("authors", [])
        if authors:
            lines.append(f"  author = {{{' and '.join(authors)}}},")

        lines.append(f"  year = {{{ref.get('year', 2024)}}},")

        if ref.get("journal"):
            lines.append(f"  journal = {{{ref['journal']}}},")

        if ref.get("doi"):
            lines.append(f"  doi = {{{ref['doi']}}},")

        lines.append("}")

        return "\n".join(lines)

    def export_dashboard_html(
        self,
        stats: Dict[str, Any],
        recent_discoveries: List[Dict],
        filename: str = "dashboard.html",
    ) -> str:
        """Export HTML dashboard."""
        filepath = self.output_dir / filename

        html = f"""<!DOCTYPE html>
<html>
<head>
    <title>TURBO-CDI Dashboard</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 40px; background: #0a0a0a; color: #e0e0e0; }}
        .header {{ text-align: center; margin-bottom: 40px; }}
        .stats {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin-bottom: 40px; }}
        .stat-card {{ background: #1a1a2e; padding: 20px; border-radius: 10px; border-left: 4px solid #00d4ff; }}
        .stat-value {{ font-size: 2em; color: #00d4ff; font-weight: bold; }}
        .discoveries {{ background: #1a1a2e; padding: 20px; border-radius: 10px; }}
        .discovery {{ border-bottom: 1px solid #333; padding: 15px 0; }}
        .discovery:last-child {{ border-bottom: none; }}
        .confidence {{ color: #00ff88; }}
        .timestamp {{ color: #666; font-size: 0.9em; }}
        h1 {{ color: #00d4ff; }}
        h2 {{ color: #ff00ff; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>⚡ TURBO-CDI Dashboard</h1>
        <p>Scientific Hypothesis Generation Engine</p>
    </div>
    
    <div class="stats">
        <div class="stat-card">
            <div class="stat-value">{stats.get("discoveries", 0)}</div>
            <div>Total Discoveries</div>
        </div>
        <div class="stat-card">
            <div class="stat-value">{stats.get("patterns", 0)}</div>
            <div>Patterns Stored</div>
        </div>
        <div class="stat-card">
            <div class="stat-value">{stats.get("validated", 0)}</div>
            <div>Validated</div>
        </div>
        <div class="stat-card">
            <div class="stat-value">{stats.get("avg_confidence", 0):.2f}</div>
            <div>Avg Confidence</div>
        </div>
    </div>
    
    <div class="discoveries">
        <h2>Recent Discoveries</h2>
"""

        for disc in recent_discoveries[:10]:
            html += f"""
        <div class="discovery">
            <div><strong>{disc.get("hypothesis", "N/A")[:100]}...</strong></div>
            <div class="timestamp">{disc.get("created_at", "N/A")} | Domain: {disc.get("domain", "general")}</div>
            <div class="confidence">Confidence: {disc.get("confidence", 0):.2f}</div>
        </div>
"""

        html += """
    </div>
    
    <footer style="text-align: center; margin-top: 40px; color: #666;">
        <p>Generated by TURBO-CDI v3.0</p>
    </footer>
</body>
</html>
"""

        with open(filepath, "w") as f:
            f.write(html)

        return str(filepath)

    def export_json(self, data: Dict[str, Any], filename: str = "export.json") -> str:
        """Export as JSON."""
        filepath = self.output_dir / filename

        with open(filepath, "w") as f:
            json.dump(data, f, indent=2, default=str)

        return str(filepath)
