#!/usr/bin/env python3
"""
Regenerate i18n.go from TOML files.
Produces: const LangEN/RU/ZH/etc. + translations map[Lang]map[string]string
"""
import re
import sys
from pathlib import Path


def parse_toml(path: Path) -> dict:
    out = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" in line and not line.startswith("["):
            k, _, v = line.partition("=")
            k = k.strip()
            v = v.strip()
            if v.startswith('"') and v.endswith('"'):
                v = v[1:-1]
            out[k] = v
    return out


LANG_CODES = ["en", "ru", "zh", "ja", "de", "ar", "hi"]
LANG_LABELS = ["LangEN", "LangRU", "LangZH", "LangJA", "LangDE", "LangAR", "LangHI"]


def go_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def main():
    i18n_dir = Path(sys.argv[1])
    out_path = Path(sys.argv[2])

    langs = {}
    for code, label in zip(LANG_CODES, LANG_LABELS):
        path = i18n_dir / f"{code}.toml"
        if not path.exists():
            print(f"WARN: {path} missing", file=sys.stderr)
            langs[code] = {}
            continue
        langs[code] = parse_toml(path)
        print(f"  {code}: {len(langs[code])} keys")

    # Get all unique keys (use EN as canonical)
    all_keys = sorted(set(langs["en"].keys()))
    for code in LANG_CODES:
        for k in langs[code]:
            if k not in all_keys:
                all_keys.append(k)
    all_keys.sort()
    print(f"Total unique keys: {len(all_keys)}")

    # Build Go source
    lines = []
    lines.append("// Package i18n provides translation lookups for the TUI v9.")
    lines.append("// Code generated by translate-pipeline/regen_i18n.py from .toml files. DO NOT EDIT.")
    lines.append("package i18n")
    lines.append("")
    lines.append('import (')
    lines.append('\t"bufio"')
    lines.append('\t"os"')
    lines.append('\t"regexp"')
    lines.append('\t"strings"')
    lines.append('\t"sync"')
    lines.append(')')
    lines.append("")
    lines.append("type Lang string")
    lines.append("")
    lines.append("const (")
    for code, label in zip(LANG_CODES, LANG_LABELS):
        lines.append(f'\t{label} Lang = "{code}"')
    lines.append(")")
    lines.append("")
    lines.append("var (")
    lines.append("\tcurrentLangMu sync.RWMutex")
    lines.append("\tcurrentLang   = LangEN")
    lines.append(")")
    lines.append("")
    lines.append("var translations = map[Lang]map[string]string{")
    for code, label in zip(LANG_CODES, LANG_LABELS):
        kv = langs[code]
        kv_pairs = ", ".join(
            f'"{k}": "{go_escape(v)}"'
            for k, v in sorted(kv.items())
        )
        lines.append(f"\t{label}: {{{kv_pairs}}},")
    lines.append("}")
    lines.append("")
    lines.append("func SetLang(l Lang) {")
    lines.append("\tcurrentLangMu.Lock()")
    lines.append("\tdefer currentLangMu.Unlock()")
    lines.append("\tcurrentLang = l")
    lines.append("}")
    lines.append("")
    lines.append("func GetLang() Lang {")
    lines.append("\tcurrentLangMu.RLock()")
    lines.append("\tdefer currentLangMu.RUnlock()")
    lines.append("\treturn currentLang")
    lines.append("}")
    lines.append("")
    lines.append("func Translations() map[Lang]map[string]string {")
    lines.append("\tcp := make(map[Lang]map[string]string, len(translations))")
    lines.append("\tfor k, v := range translations {")
    lines.append("\t\tinner := make(map[string]string, len(v))")
    lines.append("\t\tfor ik, iv := range v {")
    lines.append("\t\t\tinner[ik] = iv")
    lines.append("\t\t}")
    lines.append("\tcp[k] = inner")
    lines.append("\t}")
    lines.append("\treturn cp")
    lines.append("}")
    lines.append("")
    lines.append("// T returns the translation for key in the current language, or the key itself if missing.")
    lines.append("func T(key string) string {")
    lines.append("\tcurrentLangMu.RLock()")
    lines.append("\tlang := currentLang")
    lines.append("\tcurrentLangMu.RUnlock()")
    lines.append("\treturn TFor(key, lang)")
    lines.append("}")
    lines.append("")
    lines.append("// TFor returns the translation for key in the specified language,")
    lines.append("// falling back to English, then to the key itself.")
    lines.append("func TFor(key string, lang Lang) string {")
    lines.append("\tcurrentLangMu.RLock()")
    lines.append("\tdefer currentLangMu.RUnlock()")
    lines.append("\tif val, ok := translations[lang][key]; ok {")
    lines.append("\t\treturn val")
    lines.append("\t}")
    lines.append("\tif val, ok := translations[LangEN][key]; ok {")
    lines.append("\t\treturn val")
    lines.append("\t}")
    lines.append("\treturn key")
    lines.append("}")
    lines.append("")
    lines.append("// SetTranslations overrides translations for a given language.")
    lines.append("func SetTranslations(lang Lang, m map[string]string) {")
    lines.append("\tcurrentLangMu.Lock()")
    lines.append("\tdefer currentLangMu.Unlock()")
    lines.append("\tif m == nil {")
    lines.append("\t\treturn")
    lines.append("\t}")
    lines.append("\ttranslations[lang] = m")
    lines.append("}")
    lines.append("")
    lines.append("// LoadLangFromToml loads translations from a TOML file.")
    lines.append("func LoadLangFromToml(path string, lang Lang) error {")
    lines.append('\tf, err := os.Open(path)')
    lines.append("\tif err != nil {")
    lines.append("\t\treturn err")
    lines.append("\t}")
    lines.append("\tdefer f.Close()")
    lines.append("\tm := translations[lang]")
    lines.append("\tif m == nil {")
    lines.append("\t\tm = map[string]string{}")
    lines.append("\t\ttranslations[lang] = m")
    lines.append("\t}")
    lines.append("\tscanner := bufio.NewScanner(f)")
    lines.append('\tkeyRe := regexp.MustCompile(`^([a-z0-9_.]+)\\s*=\\s*"([^"]*)"\\s*$`)')
    lines.append("\tfor scanner.Scan() {")
    lines.append("\t\tline := strings.TrimSpace(scanner.Text())")
    lines.append('\t\tif line == "" || strings.HasPrefix(line, "#") {')
    lines.append("\t\t\tcontinue")
    lines.append("\t\t}")
    lines.append("\t\tmatches := keyRe.FindStringSubmatch(line)")
    lines.append("\t\tif len(matches) == 3 {")
    lines.append("\t\t\tm[matches[1]] = matches[2]")
    lines.append("\t\t}")
    lines.append("\t}")
    lines.append("\treturn scanner.Err()")
    lines.append("}")

    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"\nWrote {out_path} ({out_path.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
