"""First-run configuration wizard for c4reqber desktop and CLI."""
from __future__ import annotations

import os
from pathlib import Path

import typer
from rich.console import Console
from rich.prompt import Confirm, Prompt

console = Console()

CONFIG_DIR = Path.home() / ".c4reqber"
CONFIG_PATH = CONFIG_DIR / "config.toml"


def config_exists() -> bool:
    return CONFIG_PATH.is_file()


def _read_config_sections() -> dict[str, dict[str, str]]:
    if not CONFIG_PATH.is_file():
        return {}
    try:
        import toml

        raw = toml.load(CONFIG_PATH)
    except Exception:
        return {}
    if not isinstance(raw, dict):
        return {}
    out: dict[str, dict[str, str]] = {}
    for section, values in raw.items():
        if isinstance(values, dict):
            out[str(section)] = {str(k): str(v) for k, v in values.items()}
    return out


def load_existing() -> dict[str, str]:
    sections = _read_config_sections()
    core = sections.get("core", {})
    auth = sections.get("auth", {})
    llm = sections.get("llm", {})
    keys = sections.get("keys", {})
    return {
        "api_url": core.get("api_url", ""),
        "language": core.get("language", ""),
        "demo_mode": core.get("demo_mode", ""),
        "email": auth.get("email", ""),
        "password": auth.get("password", ""),
        "name": auth.get("name", ""),
        "openrouter_api_key": llm.get("openrouter_api_key", ""),
        "deepseek_api_key": keys.get("deepseek_api_key", ""),
        "brave_api_key": keys.get("brave_api_key", ""),
        "tavily_api_key": keys.get("tavily_api_key", ""),
        "exa_api_key": keys.get("exa_api_key", ""),
        "xai_api_key": keys.get("xai_api_key", ""),
        "lean4_path": keys.get("lean4_path", ""),
    }


def write_config(values: dict[str, str]) -> Path:
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    lines = [
        "# c4reqber user configuration — generated by blast init",
        "# This file + models.json + ~/.c4reqber/*.json power desktop/CLI/TUI",
        "",
        "[core]",
        f'api_url = "{values.get("api_url", "http://127.0.0.1:8000")}"',
        f'language = "{values.get("language", "en")}"',
        f'demo_mode = {str(values.get("demo_mode", "false")).lower()}',
        "",
        "[auth]",
        f'email = "{values.get("email", "")}"',
        f'password = "{values.get("password", "")}"',
        f'name = "{values.get("name", "c4reqber-user")}"',
        "",
        "[llm]",
        f'openrouter_api_key = "{values.get("openrouter_api_key", "")}"',
        "",
        "[keys]",
        f'deepseek_api_key = "{values.get("deepseek_api_key", "")}"',
        f'brave_api_key = "{values.get("brave_api_key", "")}"',
        f'tavily_api_key = "{values.get("tavily_api_key", "")}"',
        f'exa_api_key = "{values.get("exa_api_key", "")}"',
        f'xai_api_key = "{values.get("xai_api_key", "")}"',
        f'lean4_path = "{values.get("lean4_path", "")}"',
        "",
    ]
    CONFIG_PATH.write_text("\n".join(lines), encoding="utf-8")
    return CONFIG_PATH


def run_init_wizard(*, force: bool = False) -> Path:
    existing = load_existing()
    if config_exists() and not force:
        if not Confirm.ask(f"Overwrite {CONFIG_PATH}?", default=False):
            console.print(f"[dim]Keeping existing config at {CONFIG_PATH}[/]")
            return CONFIG_PATH

    console.print("[bold]c4reqber setup[/bold] — configure API, auth, and LLM keys\n")

    api_url = Prompt.ask(
        "API base URL",
        default=existing.get("api_url", os.getenv("C4_API_URL", "http://127.0.0.1:8000")),
    )
    language = Prompt.ask("UI language (en/ru/zh/de/ja/hi/ar)", default=existing.get("language", "en"))
    demo_mode = Confirm.ask("Demo mode (no live API auth)?", default=False)

    email = ""
    password = ""
    name = "c4reqber-user"
    if not demo_mode:
        email = Prompt.ask(
            "API email",
            default=existing.get("email", os.getenv("C4_API_EMAIL", "")),
        )
        password = Prompt.ask(
            "API password",
            password=True,
            default=existing.get("password", os.getenv("C4_API_PASSWORD", "")),
        )
        name = Prompt.ask("Display name", default=existing.get("name", "c4reqber-user"))

    openrouter = Prompt.ask(
        "OpenRouter API key (optional, BYOK)",
        password=True,
        default=existing.get("openrouter_api_key", os.getenv("OPENROUTER_API_KEY", "")),
    )

    # Production polish: ask for more essential keys in the cool desktop app
    deepseek = Prompt.ask(
        "DeepSeek API key (recommended cheap/fast)",
        password=True,
        default=existing.get("deepseek_api_key", os.getenv("DEEPSEEK_API_KEY", "")),
    )
    brave = Prompt.ask(
        "Brave Search API key (for web augmentation)",
        password=True,
        default=existing.get("brave_api_key", os.getenv("BRAVE_API_KEY", "")),
    )
    tavily = Prompt.ask(
        "Tavily API key (high-quality search, recommended)",
        password=True,
        default=existing.get("tavily_api_key", os.getenv("TAVILY_API_KEY", "")),
    )
    exa = Prompt.ask(
        "Exa API key (semantic web search)",
        password=True,
        default=existing.get("exa_api_key", os.getenv("EXA_API_KEY", "")),
    )
    xai = Prompt.ask(
        "XAI / Grok API key (optional)",
        password=True,
        default=existing.get("xai_api_key", os.getenv("XAI_API_KEY", "")),
    )
    lean_path = Prompt.ask(
        "Lean4 path (optional, for formal verification; leave empty to auto-detect)",
        default=existing.get("lean4_path", os.getenv("LEAN4_PATH", "")),
    )

    # For polished desktop "all settings" app: allow choosing initial LLM tier
    tier = Prompt.ask(
        "Initial LLM cost tier (balanced/premium/budget/local)",
        default="balanced",
    ).lower().strip()
    if tier not in ("balanced", "premium", "budget", "local", "ultra_budget"):
        tier = "balanced"

    path = write_config(
        {
            "api_url": api_url,
            "language": language,
            "demo_mode": "true" if demo_mode else "false",
            "email": email,
            "password": password,
            "name": name,
            "openrouter_api_key": openrouter,
            "deepseek_api_key": deepseek,
            "brave_api_key": brave,
            "tavily_api_key": tavily,
            "exa_api_key": exa,
            "xai_api_key": xai,
            "lean4_path": lean_path,
        }
    )

    # Polish: also seed models.json with chosen tier for "all settings" ready immediately
    try:
        from src.llm.model_assignment import ModelAssignment
        models_path = CONFIG_DIR / "models.json"
        if not models_path.exists():
            assignment = ModelAssignment.create_default(tier)
            assignment.save(models_path)
    except Exception:
        pass

    console.print(f"\n[green]✓[/] Config written to [bold]{path}[/]")
    console.print("[dim]Desktop/CLI/TUI use this + models.json. Exported envs:[/]")
    console.print("[dim]  Core + OPENROUTER/DEEPSEEK/BRAVE/TAVILY/EXA/XAI keys + LEAN4_PATH[/]")
    return path


def apply_config_to_env() -> None:
    """Export config.toml values into os.environ when not already set."""
    sections = _read_config_sections()
    if not sections:
        return
    core = sections.get("core", {})
    auth = sections.get("auth", {})
    llm = sections.get("llm", {})
    keys = sections.get("keys", {})
    mapping = {
        "C4_API_URL": core.get("api_url"),
        "C4_LANG": core.get("language"),
        "C4_API_EMAIL": auth.get("email"),
        "C4_API_PASSWORD": auth.get("password"),
        "C4_API_NAME": auth.get("name"),
        "OPENROUTER_API_KEY": llm.get("openrouter_api_key"),
        "DEEPSEEK_API_KEY": keys.get("deepseek_api_key"),
        "BRAVE_API_KEY": keys.get("brave_api_key"),
        "TAVILY_API_KEY": keys.get("tavily_api_key"),
        "EXA_API_KEY": keys.get("exa_api_key"),
        "XAI_API_KEY": keys.get("xai_api_key"),
        "LEAN4_PATH": keys.get("lean4_path"),
    }
    if core.get("demo_mode") in ("true", "1", "True"):
        mapping["C4_DEMO_AUTH"] = "1"
    for key, val in mapping.items():
        if val and not os.getenv(key):
            os.environ[key] = str(val)