"""
TURBO-CDI: Agent Mode v4.1
Autonomous scientific discovery agent

Usage:
    turbo agent "Increase battery density" --time 1h --output report.md

The agent:
1. Analyzes the problem
2. Generates N hypotheses using C4+TRIZ+Analogy
3. Evaluates falsifiability of each
4. Ranks by confidence/cost
5. Creates validation plans
6. Returns full report
"""

import asyncio
import json
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

from rich.console import Console
from rich.panel import Panel
from rich.progress import BarColumn, Progress, SpinnerColumn, TextColumn
from rich.table import Table

from src.analogy import AnalogyResult, get_analogy_engine
from src.graph.knowledge_graph import get_knowledge_graph
from src.models.pydantic_models import C4StateModel, DiscoveryModel
from src.triz import get_c4_triz_bridge
from src.validation import FalsifiabilityCriterion, get_validation_tracker


console = Console()


@dataclass
class AgentHypothesis:
    """A hypothesis generated by the agent."""

    id: str
    problem: str
    hypothesis: str
    mechanism: str
    c4_path: list[str]
    triz_principles: list[int]
    analogies: list[AnalogyResult]
    confidence: float
    falsifiability_criteria: list[FalsifiabilityCriterion]
    estimated_validation_cost: float  # USD
    estimated_time_to_validate: str  # e.g., "2 weeks"
    domain: str
    generation_method: str  # "c4", "analogy", "triz", "hybrid"


@dataclass
class AgentReport:
    """Full report from agent execution."""

    query: str
    start_time: datetime
    end_time: datetime
    total_hypotheses: int
    hypotheses: list[AgentHypothesis]
    rankings: dict[str, list[str]]  # By confidence, cost, speed
    summary: str
    recommendations: list[str]


class ScientificDiscoveryAgent:
    """
    Autonomous agent for scientific discovery.

    Combines C4, TRIZ, and Analogy methods to generate
    and rank hypotheses without user intervention.
    """

    def __init__(self):
        self.kg = get_knowledge_graph()
        self.analogy = get_analogy_engine()
        self.triz = get_c4_triz_bridge()
        self.validator = get_validation_tracker()
        self._hypothesis_counter = 0

    async def discover(
        self,
        problem: str,
        time_budget: str | None = None,
        max_hypotheses: int = 10,
        domains: list[str] | None = None,
    ) -> AgentReport:
        """
        Autonomous discovery process.

        Args:
            problem: Natural language problem description
            time_budget: e.g., "1h", "30m" (for progress reporting)
            max_hypotheses: Maximum number to generate
            domains: Domains to explore (auto-detected if None)

        Returns:
            AgentReport with hypotheses and recommendations
        """
        start_time = datetime.now()

        console.print("[bold blue]🔬 Scientific Discovery Agent[/bold blue]")
        console.print(f"Problem: {problem}")
        console.print(f"Max hypotheses: {max_hypotheses}\n")

        hypotheses: list[AgentHypothesis] = []

        with Progress(
            SpinnerColumn(),
            TextColumn("[progress.description]{task.description}"),
            BarColumn(),
            TextColumn("[progress.percentage]{task.percentage:>3.0f}%"),
            console=console,
        ) as progress:
            # Step 1: Analyze problem
            task1 = progress.add_task("[cyan]Analyzing problem...", total=100)
            await asyncio.sleep(0.5)  # Simulate analysis
            detected_domains = domains or self._detect_domains(problem)
            progress.update(task1, completed=100)

            # Step 2: Generate via C4+TRIZ
            task2 = progress.add_task("[cyan]Generating via C4+TRIZ...", total=100)
            c4_hypotheses = await self._generate_c4_triz(problem, detected_domains)
            hypotheses.extend(c4_hypotheses)
            progress.update(task2, completed=100)

            # Step 3: Generate via Analogy
            task3 = progress.add_task(
                "[cyan]Exploring cross-domain analogies...", total=100
            )
            analogy_hypotheses = await self._generate_analogies(
                problem, detected_domains
            )
            hypotheses.extend(analogy_hypotheses)
            progress.update(task3, completed=100)

            # Step 4: Generate via Hybrid
            task4 = progress.add_task("[cyan]Creating hybrid solutions...", total=100)
            hybrid_hypotheses = await self._generate_hybrid(hypotheses)
            hypotheses.extend(hybrid_hypotheses)
            progress.update(task4, completed=100)

            # Step 5: Evaluate falsifiability
            task5 = progress.add_task(
                "[cyan]Evaluating falsifiability...", total=len(hypotheses)
            )
            for h in hypotheses:
                h.falsifiability_criteria = await self._generate_falsifiability(h)
                progress.advance(task5)

            # Step 6: Rank and filter
            task6 = progress.add_task("[cyan]Ranking hypotheses...", total=100)
            hypotheses = self._rank_hypotheses(hypotheses)[:max_hypotheses]
            progress.update(task6, completed=100)

            # Step 7: Estimate costs
            task7 = progress.add_task(
                "[cyan]Estimating validation costs...", total=len(hypotheses)
            )
            for h in hypotheses:
                h.estimated_validation_cost = self._estimate_cost(h)
                h.estimated_time_to_validate = self._estimate_time(h)
                progress.advance(task7)

        end_time = datetime.now()

        # Generate rankings
        rankings = {
            "by_confidence": [
                h.id
                for h in sorted(hypotheses, key=lambda x: x.confidence, reverse=True)
            ],
            "by_cost": [
                h.id
                for h in sorted(hypotheses, key=lambda x: x.estimated_validation_cost)
            ],
            "by_speed": [
                h.id
                for h in sorted(
                    hypotheses,
                    key=lambda x: self._parse_time(x.estimated_time_to_validate),
                )
            ],
        }

        # Generate report
        report = AgentReport(
            query=problem,
            start_time=start_time,
            end_time=end_time,
            total_hypotheses=len(hypotheses),
            hypotheses=hypotheses,
            rankings=rankings,
            summary=self._generate_summary(hypotheses),
            recommendations=self._generate_recommendations(hypotheses),
        )

        return report

    def _detect_domains(self, problem: str) -> list[str]:
        """Auto-detect relevant domains from problem description."""
        keywords = {
            "battery": ["energy", "chemistry", "materials"],
            "software": ["computer_science", "mathematics"],
            "biological": ["biology", "chemistry"],
            "mechanical": ["physics", "engineering"],
            "economic": ["economics", "mathematics"],
            "algorithm": ["computer_science", "mathematics"],
            "protein": ["biology", "chemistry"],
            "neural": ["biology", "computer_science"],
        }

        problem_lower = problem.lower()
        detected = set()

        for keyword, domains in keywords.items():
            if keyword in problem_lower:
                detected.update(domains)

        return list(detected) if detected else ["general"]

    async def _generate_c4_triz(
        self, problem: str, domains: list[str]
    ) -> list[AgentHypothesis]:
        """Generate hypotheses using C4+TRIZ methodology."""
        hypotheses = []

        # Try different contradiction formulations
        contradictions = [
            ("performance", "cost"),
            ("speed", "reliability"),
            ("features", "simplicity"),
        ]

        for improve, worsen in contradictions[:2]:
            solution = self.triz.generate_c4_triz_path(problem, (improve, worsen))

            self._hypothesis_counter += 1
            h = AgentHypothesis(
                id=f"h_c4_{self._hypothesis_counter}",
                problem=problem,
                hypothesis=f"Solution via {improve} vs {worsen} optimization",
                mechanism=f"Apply C4 path: {' → '.join(solution['c4_path'])}",
                c4_path=solution["c4_path"],
                triz_principles=solution["triz_principles"],
                analogies=[],
                confidence=0.6
                + len(solution["c4_path"]) * 0.05,  # More steps = higher confidence
                falsifiability_criteria=[],
                estimated_validation_cost=0.0,
                estimated_time_to_validate="",
                domain=domains[0] if domains else "general",
                generation_method="c4_triz",
            )
            hypotheses.append(h)

        return hypotheses

    async def _generate_analogies(
        self, problem: str, domains: list[str]
    ) -> list[AgentHypothesis]:
        """Generate hypotheses via cross-domain analogies."""
        hypotheses = []

        # Try cross-domain mappings
        source_domains = domains
        target_domains = ["biology", "physics", "computer_science", "economics"]

        for source in source_domains:
            for target in target_domains:
                if source != target:
                    # Find analogies between domains
                    analogies = self.analogy.discover_cross_domain_analogies(
                        source, target, max_analogies=3
                    )

                    for analogy in analogies[:1]:  # Top 1 per domain pair
                        self._hypothesis_counter += 1
                        h = AgentHypothesis(
                            id=f"h_ana_{self._hypothesis_counter}",
                            problem=problem,
                            hypothesis=f"Apply {analogy.source_concept} ({source}) → {analogy.target_concept} ({target})",
                            mechanism=f"Cross-domain analogy with confidence {analogy.confidence:.2f}",
                            c4_path=["sigma", "iota"],  # Abstraction + Integration
                            triz_principles=[
                                6,
                                24,
                                28,
                            ],  # Universality, Mediator, Mechanics Substitution
                            analogies=[analogy],
                            confidence=analogy.confidence,
                            falsifiability_criteria=[],
                            estimated_validation_cost=0.0,
                            estimated_time_to_validate="",
                            domain=source,
                            generation_method="analogy",
                        )
                        hypotheses.append(h)

        return hypotheses

    async def _generate_hybrid(
        self, existing: list[AgentHypothesis]
    ) -> list[AgentHypothesis]:
        """Generate hybrid hypotheses by combining existing ones."""
        if len(existing) < 2:
            return []

        hypotheses = []

        # Combine top C4 with top Analogy
        c4_h = next((h for h in existing if h.generation_method == "c4_triz"), None)
        ana_h = next((h for h in existing if h.generation_method == "analogy"), None)

        if c4_h and ana_h:
            self._hypothesis_counter += 1
            h = AgentHypothesis(
                id=f"h_hyb_{self._hypothesis_counter}",
                problem=c4_h.problem,
                hypothesis=f"Hybrid: {c4_h.hypothesis} + {ana_h.hypothesis}",
                mechanism=f"Combine C4 path with analogy from {ana_h.analogies[0].source_domain if ana_h.analogies else 'unknown'}",
                c4_path=c4_h.c4_path + ["iota"],  # Add integration step
                triz_principles=list(set(c4_h.triz_principles + ana_h.triz_principles)),
                analogies=ana_h.analogies,
                confidence=(c4_h.confidence + ana_h.confidence)
                / 2
                * 1.1,  # Boost for hybrid
                falsifiability_criteria=[],
                estimated_validation_cost=0.0,
                estimated_time_to_validate="",
                domain=c4_h.domain,
                generation_method="hybrid",
            )
            # Cap confidence at 0.95
            h.confidence = min(h.confidence, 0.95)
            hypotheses.append(h)

        return hypotheses

    async def _generate_falsifiability(
        self, hypothesis: AgentHypothesis
    ) -> list[FalsifiabilityCriterion]:
        """Generate falsifiability criteria for a hypothesis."""
        # Simplified - in real implementation would use LLM
        criteria = [
            FalsifiabilityCriterion(
                statement=f"If {hypothesis.domain} metric does not improve by 20%, hypothesis is false",
                measurement=f"Measure {hypothesis.domain} performance",
                threshold="20% improvement",
                difficulty="medium",
            ),
            FalsifiabilityCriterion(
                statement="If side effects exceed benefits, hypothesis is false",
                measurement="Measure side effects vs benefits",
                threshold="Side effects < 10% of benefits",
                difficulty="hard",
            ),
        ]
        return criteria

    def _rank_hypotheses(
        self, hypotheses: list[AgentHypothesis]
    ) -> list[AgentHypothesis]:
        """Rank hypotheses by composite score."""

        def score(h: AgentHypothesis) -> float:
            # Composite: confidence * (1/cost) * speed_factor
            cost_factor = 1.0 / (1 + h.estimated_validation_cost / 10000)
            return h.confidence * cost_factor

        return sorted(hypotheses, key=score, reverse=True)

    def _estimate_cost(self, hypothesis: AgentHypothesis) -> float:
        """Estimate validation cost in USD."""
        # Simplified cost model
        base_cost = 5000  # Base experiment cost

        # Adjust by method
        multipliers = {
            "c4_triz": 1.0,
            "analogy": 1.2,  # Cross-domain may need more setup
            "hybrid": 1.5,  # More complex to validate
        }

        return base_cost * multipliers.get(hypothesis.generation_method, 1.0)

    def _estimate_time(self, hypothesis: AgentHypothesis) -> str:
        """Estimate time to validate."""
        times = {
            "c4_triz": "2-4 weeks",
            "analogy": "4-6 weeks",
            "hybrid": "6-8 weeks",
        }
        return times.get(hypothesis.generation_method, "4 weeks")

    def _parse_time(self, time_str: str) -> int:
        """Parse time string to weeks for sorting."""
        import re

        numbers = re.findall(r"\d+", time_str)
        if numbers:
            return int(numbers[0])
        return 4

    def _generate_summary(self, hypotheses: list[AgentHypothesis]) -> str:
        """Generate executive summary."""
        methods = {}
        for h in hypotheses:
            methods[h.generation_method] = methods.get(h.generation_method, 0) + 1

        avg_confidence = (
            sum(h.confidence for h in hypotheses) / len(hypotheses) if hypotheses else 0
        )
        total_cost = sum(h.estimated_validation_cost for h in hypotheses)

        return f"""Generated {len(hypotheses)} hypotheses across {len(methods)} methods.
Average confidence: {avg_confidence:.1%}
Total validation budget: ${total_cost:,.0f}
Top method: {max(methods, key=methods.get) if methods else "N/A"}
"""

    def _generate_recommendations(self, hypotheses: list[AgentHypothesis]) -> list[str]:
        """Generate actionable recommendations."""
        if not hypotheses:
            return ["No hypotheses generated. Try rephrasing the problem."]

        top = hypotheses[0]
        return [
            f"Start with hypothesis {top.id} (confidence: {top.confidence:.1%})",
            f"Budget ${top.estimated_validation_cost:,.0f} for validation",
            f"Estimated time to validate: {top.estimated_time_to_validate}",
            "Consider parallel validation of top 3 hypotheses",
        ]

    def export_report(self, report: AgentReport, output_path: str):
        """Export report to file (Markdown or JSON)."""
        path = Path(output_path)

        if path.suffix == ".json":
            # JSON export
            data = {
                "query": report.query,
                "duration_seconds": (
                    report.end_time - report.start_time
                ).total_seconds(),
                "total_hypotheses": report.total_hypotheses,
                "summary": report.summary,
                "recommendations": report.recommendations,
                "hypotheses": [
                    {
                        "id": h.id,
                        "hypothesis": h.hypothesis,
                        "confidence": h.confidence,
                        "method": h.generation_method,
                        "c4_path": h.c4_path,
                        "triz_principles": h.triz_principles,
                        "validation_cost": h.estimated_validation_cost,
                        "validation_time": h.estimated_time_to_validate,
                    }
                    for h in report.hypotheses
                ],
            }
            with open(path, "w") as f:
                json.dump(data, f, indent=2)

        else:
            # Markdown export
            md = f"""# Scientific Discovery Report

**Query:** {report.query}
**Generated:** {report.start_time.strftime("%Y-%m-%d %H:%M")}
**Duration:** {(report.end_time - report.start_time).total_seconds() / 60:.1f} minutes

## Summary

{report.summary}

## Top Recommendations

"""
            for i, rec in enumerate(report.recommendations, 1):
                md += f"{i}. {rec}\n"

            md += "\n## Hypotheses\n\n"

            for h in report.hypotheses:
                md += f"""### {h.id} (Confidence: {h.confidence:.1%})

**Hypothesis:** {h.hypothesis}

**Mechanism:** {h.mechanism}

**Method:** {h.generation_method}

**C4 Path:** {" → ".join(h.c4_path)}

**TRIZ Principles:** {", ".join(map(str, h.triz_principles))}

**Validation:**
- Estimated cost: ${h.estimated_validation_cost:,.0f}
- Estimated time: {h.estimated_time_to_validate}

---

"""

            with open(path, "w") as f:
                f.write(md)

        console.print(f"[green]✓ Report exported to {output_path}[/green]")


# ═══════════════════════════════════════════════════════════════════
# SINGLETON INSTANCE
# ═══════════════════════════════════════════════════════════════════

_agent: ScientificDiscoveryAgent | None = None


def get_agent() -> ScientificDiscoveryAgent:
    """Get singleton agent instance."""
    global _agent
    if _agent is None:
        _agent = ScientificDiscoveryAgent()
    return _agent
