"""c4-cdi-turbo System Dynamics Engine."""

from .archetypes import (
    ARCHETYPE_BY_NAME,
    ARCHETYPES,
    ESCALATION,
    FIXES_THAT_FAIL,
    LIMITS_TO_GROWTH,
    SHIFTING_THE_BURDEN,
    TRAGEDY_OF_THE_COMMONS,
    Archetype,
    best_archetype_match,
    build_escalation,
    build_fixes_that_fail,
    build_limits_to_growth,
    build_shifting_the_burden,
    build_tragedy_of_the_commons,
    detect_archetype,
    model_to_cld,
    simulate_archetype,
)
from .causal_loop import (
    CausalLoopDiagram,
    CLDLink,
    CLDNode,
    LoopType,
    Polarity,
    adjacency_matrix,
    eigenvalue_analysis,
)
from .stock_flow import (
    Auxiliary,
    CompiledSystem,
    Flow,
    Stock,
    SystemSpec,
    adaptive_integrate,
    adaptive_rk45_step,
    rk4_integrate,
    rk4_step,
)


__all__ = [
    # stock_flow
    "Stock",
    "Flow",
    "Auxiliary",
    "SystemSpec",
    "CompiledSystem",
    "rk4_step",
    "rk4_integrate",
    "adaptive_rk45_step",
    "adaptive_integrate",
    # causal_loop
    "Polarity",
    "LoopType",
    "CLDNode",
    "CLDLink",
    "CausalLoopDiagram",
    "adjacency_matrix",
    "eigenvalue_analysis",
    # archetypes
    "Archetype",
    "ARCHETYPES",
    "ARCHETYPE_BY_NAME",
    "LIMITS_TO_GROWTH",
    "SHIFTING_THE_BURDEN",
    "TRAGEDY_OF_THE_COMMONS",
    "ESCALATION",
    "FIXES_THAT_FAIL",
    "build_limits_to_growth",
    "build_shifting_the_burden",
    "build_tragedy_of_the_commons",
    "build_escalation",
    "build_fixes_that_fail",
    "model_to_cld",
    "detect_archetype",
    "best_archetype_match",
    "simulate_archetype",
]
