"""Metaprograms package init."""

from .attractors import (
    ALL_STATES,
    BASIN_STATES,
    DANGEROUS_STATES,
    PHI,
    PHI_DESCRIPTION,
    PHI_NAME,
    AttractorState,
    basin_coverage,
    classify_state,
    distance_to_phi,
    get_basin_states,
    get_dangerous_states,
    get_state,
    suggest_phi_shift,
)
from .core import (
    ALL_METAPROGRAMS,
    CATEGORY_MAP,
    METAPROGRAM_BY_CODE,
    AgencyAxis,
    C4Coord,
    Metaprogram,
    ScaleAxis,
    TemporalAxis,
    count_metaprograms,
    get_by_category,
    get_metaprogram,
    hamming_distance,
)
from .profiler import (
    MPScore,
    UserProfile,
    detect_profile,
    profile_to_attractor_cluster,
    suggest_shifts,
)


__all__ = [
    "ALL_METAPROGRAMS",
    "CATEGORY_MAP",
    "METAPROGRAM_BY_CODE",
    "C4Coord",
    "Metaprogram",
    "TemporalAxis",
    "ScaleAxis",
    "AgencyAxis",
    "hamming_distance",
    "get_metaprogram",
    "get_by_category",
    "count_metaprograms",
    "UserProfile",
    "MPScore",
    "detect_profile",
    "suggest_shifts",
    "profile_to_attractor_cluster",
    "PHI",
    "PHI_NAME",
    "PHI_DESCRIPTION",
    "AttractorState",
    "classify_state",
    "get_basin_states",
    "get_dangerous_states",
    "get_state",
    "distance_to_phi",
    "suggest_phi_shift",
    "basin_coverage",
    "ALL_STATES",
    "BASIN_STATES",
    "DANGEROUS_STATES",
]
