"""Discovery v8 subpackage — God Object decomposition of discovery_v8.py."""
from src.api.v8_routers.discovery.export import (
    ExportRequest,
    ExportResponse,
    _normalize_discovery_for_markdown,
    export_discovery,
)
from src.api.v8_routers.discovery.pipeline import (
    DissertationRequest,
    MultiHypothesisRequest,
    OneClickRequest,
    _build_dissertation,
    _domain_improving_param,
    _domain_worsening_param,
    _refine_hypothesis_llm,
    _run_self_critique,
    build_temporal_kg,
    detect_paradigm_shift,
    dissertation_mode,
    generate_hypothesis,
    generate_lean4_proof,
    generate_paper,
    mine_contradictions,
    multi_hypothesis_discovery,
    navigate_c4,
    one_click_discovery,
    resolve_triz,
    run_abduction,
    run_autoscanner,
    run_bayesian_conjugate_update,
    run_bayesian_model_averaging,
    run_c4_observer,
    run_causal_do_calculus,
    run_cognitive_plugins,
    run_consensus_meter,
    run_counterfactual,
    run_dempster_shafer,
    run_doe_design,
    run_empirical_validation,
    run_falsification_engine,
    run_fra_routing,
    run_matrix_dream,
    run_power_analysis,
    run_relevant_simulation,
    run_reproducibility_check,
    run_strong_inference,
    search_isomorphisms,
)
from src.api.v8_routers.discovery.search import search_knowledge


__all__ = [
    "search_knowledge",
    "navigate_c4", "resolve_triz", "run_fra_routing", "run_c4_observer",
    "search_isomorphisms", "mine_contradictions", "build_temporal_kg",
    "detect_paradigm_shift", "run_strong_inference", "run_abduction",
    "run_falsification_engine", "run_doe_design", "run_power_analysis",
    "run_reproducibility_check", "generate_hypothesis", "run_relevant_simulation",
    "run_causal_do_calculus", "run_counterfactual", "generate_lean4_proof",
    "run_bayesian_model_averaging", "run_dempster_shafer",
    "run_bayesian_conjugate_update", "run_consensus_meter",
    "run_empirical_validation", "run_autoscanner", "run_matrix_dream",
    "generate_paper", "run_cognitive_plugins",
    "_domain_improving_param", "_domain_worsening_param",
    "_run_self_critique", "_refine_hypothesis_llm", "_build_dissertation",
    "one_click_discovery", "multi_hypothesis_discovery", "dissertation_mode",
    "export_discovery", "_normalize_discovery_for_markdown",
    "OneClickRequest", "MultiHypothesisRequest", "DissertationRequest",
    "ExportRequest", "ExportResponse",
]
