#!/usr/bin/env python3
"""Export TUI v9 splash ASCII art → landing/js/splash-art.js (single source: v8 assets)."""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
GREEN_CUBE = ROOT / "src/tui/v8/splash/green_cube.txt"
EMBEDDED = ROOT / "src/tui/v9/v8_art_embedded.go"
OUT = ROOT / "landing/js/splash-art.js"

ANSI_RE = re.compile(r"\x1b\[[0-9;]*[a-zA-Z]")


def extract_go_const(name: str, src: str) -> str:
    m = re.search(rf"const {name} = `([^`]*)`", src, re.DOTALL)
    if not m:
        raise SystemExit(f"missing const {name} in {EMBEDDED}")
    return m.group(1).strip("\n")


def extract_go_var(name: str, src: str) -> str:
    m = re.search(rf"const {name} = `\n([^`]*)`", src, re.DOTALL)
    if not m:
        m = re.search(rf"var {name} = `\n([^`]*)`", src, re.DOTALL)
    if not m:
        raise SystemExit(f"missing var/const {name} in {EMBEDDED}")
    return m.group(1).strip("\n")


def js_string(s: str) -> str:
    return json_escape(s)


def json_escape(s: str) -> str:
    out: list[str] = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == "`":
            out.append("\\`")
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            pass
        elif ch == '"':
            out.append('\\"')
        else:
            out.append(ch)
    return "".join(out)


def normalize_c4r_left_wall(text: str) -> str:
    """Ensure every C4R line shares the same left margin (straight C wall)."""
    lines = text.split("\n")
    if not lines:
        return text
    lead_counts: list[int] = []
    for line in lines:
        stripped = line.lstrip(" ")
        if not stripped:
            continue
        lead_counts.append(len(line) - len(stripped))
    if not lead_counts:
        return text
    target = min(lead_counts)
    out: list[str] = []
    for line in lines:
        stripped = line.lstrip(" ")
        if not stripped:
            out.append(line)
            continue
        out.append(" " * target + stripped)
    return "\n".join(out)


def main() -> None:
    go_src = EMBEDDED.read_text(encoding="utf-8", errors="replace")
    green = GREEN_CUBE.read_text(encoding="utf-8").strip("\n")
    big_c4r = normalize_c4r_left_wall(extract_go_const("v8BigC4R", go_src).strip("\n"))
    crystal_raw = extract_go_var("v8RawANSISmall", go_src)
    crystal = "\n".join(ANSI_RE.sub("", line) for line in crystal_raw.splitlines()).strip("\n")

    OUT.write_text(
        "/* AUTO-GENERATED by scripts/export_splash_art.py — do not edit */\n"
        "window.C4_SPLASH_ART = {\n"
        f"  greenCube: `{js_string(green)}`,\n"
        f"  bigC4R: `{js_string(big_c4r)}`,\n"
        f"  crystalSeed: `{js_string(crystal)}`,\n"
        "};\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
