// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"encoding/json"
	"errors"

	"github.com/oapi-codegen/runtime"
)

// Defines values for OneClickRequestLlmTier.
const (
	C1    OneClickRequestLlmTier = "C1"
	C2    OneClickRequestLlmTier = "C2"
	C3    OneClickRequestLlmTier = "C3"
	Empty OneClickRequestLlmTier = ""
)

// Valid indicates whether the value is a known member of the OneClickRequestLlmTier enum.
func (e OneClickRequestLlmTier) Valid() bool {
	switch e {
	case C1:
		return true
	case C2:
		return true
	case C3:
		return true
	case Empty:
		return true
	default:
		return false
	}
}

// Defines values for OneClickRequestOutputMode.
const (
	Explain OneClickRequestOutputMode = "explain"
	Human   OneClickRequestOutputMode = "human"
)

// Valid indicates whether the value is a known member of the OneClickRequestOutputMode enum.
func (e OneClickRequestOutputMode) Valid() bool {
	switch e {
	case Explain:
		return true
	case Human:
		return true
	default:
		return false
	}
}

// FlashRequest defines model for FlashRequest.
type FlashRequest struct {
	Domain  *string `json:"domain,omitempty"`
	Problem string  `json:"problem"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status  *string `json:"status,omitempty"`
	Version *string `json:"version,omitempty"`
}

// JobCreatedResponse defines model for JobCreatedResponse.
type JobCreatedResponse struct {
	JobId  string `json:"job_id"`
	Status string `json:"status"`
}

// JobStatusResponse defines model for JobStatusResponse.
type JobStatusResponse struct {
	Errors      *[]string               `json:"errors,omitempty"`
	JobId       *string                 `json:"job_id,omitempty"`
	Phase       *string                 `json:"phase,omitempty"`
	PhaseDetail *string                 `json:"phase_detail,omitempty"`
	Progress    *float32                `json:"progress,omitempty"`
	Result      *map[string]interface{} `json:"result,omitempty"`
	Status      *string                 `json:"status,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string  `json:"email"`
	Name     *string `json:"name,omitempty"`
	Password string  `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	AccessToken *string `json:"access_token,omitempty"`
	TokenType   *string `json:"token_type,omitempty"`
}

// OneClickRequest defines model for OneClickRequest.
type OneClickRequest struct {
	Domain     *string                    `json:"domain,omitempty"`
	LlmTier    *OneClickRequestLlmTier    `json:"llm_tier,omitempty"`
	OutputMode *OneClickRequestOutputMode `json:"output_mode,omitempty"`
	Problem    string                     `json:"problem"`
}

// OneClickRequestLlmTier defines model for OneClickRequest.LlmTier.
type OneClickRequestLlmTier string

// OneClickRequestOutputMode defines model for OneClickRequest.OutputMode.
type OneClickRequestOutputMode string

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    string  `json:"email"`
	Name     *string `json:"name,omitempty"`
	Password string  `json:"password"`
}

// SSEBase defines model for SSEBase.
type SSEBase struct {
	JobId *string `json:"job_id,omitempty"`
	Ts    *string `json:"ts,omitempty"`
	Type  string  `json:"type"`
}

// SSEComplete defines model for SSEComplete.
type SSEComplete struct {
	Errors   *[]string               `json:"errors,omitempty"`
	JobId    *string                 `json:"job_id,omitempty"`
	Phase    *string                 `json:"phase,omitempty"`
	Progress *float32                `json:"progress,omitempty"`
	Result   *map[string]interface{} `json:"result,omitempty"`
	Status   *string                 `json:"status,omitempty"`
	Ts       *string                 `json:"ts,omitempty"`
	Type     string                  `json:"type"`
}

// SSEError defines model for SSEError.
type SSEError struct {
	Detail *string `json:"detail,omitempty"`
	JobId  *string `json:"job_id,omitempty"`
	Ts     *string `json:"ts,omitempty"`
	Type   string  `json:"type"`
}

// SSEEventEnvelope JSON payload inside SSE data lines
type SSEEventEnvelope struct {
	union json.RawMessage
}

// SSEFailed defines model for SSEFailed.
type SSEFailed struct {
	Errors   *[]string `json:"errors,omitempty"`
	JobId    *string   `json:"job_id,omitempty"`
	Phase    *string   `json:"phase,omitempty"`
	Progress *float32  `json:"progress,omitempty"`
	Status   *string   `json:"status,omitempty"`
	Ts       *string   `json:"ts,omitempty"`
	Type     string    `json:"type"`
}

// SSEPhaseProgress defines model for SSEPhaseProgress.
type SSEPhaseProgress struct {
	Detail   *string  `json:"detail,omitempty"`
	JobId    *string  `json:"job_id,omitempty"`
	Phase    *string  `json:"phase,omitempty"`
	Progress *float32 `json:"progress,omitempty"`
	Status   *string  `json:"status,omitempty"`
	Ts       *string  `json:"ts,omitempty"`
	Type     string   `json:"type"`
}

// SSESimFinished defines model for SSESimFinished.
type SSESimFinished struct {
	Engine       *string `json:"engine,omitempty"`
	EngineStatus *string `json:"engine_status,omitempty"`
	JobId        *string `json:"job_id,omitempty"`
	Pattern      *string `json:"pattern,omitempty"`
	Ts           *string `json:"ts,omitempty"`
	Type         string  `json:"type"`
	Verdict      *string `json:"verdict,omitempty"`
}

// SSESimSkipped defines model for SSESimSkipped.
type SSESimSkipped struct {
	Engine       *string `json:"engine,omitempty"`
	EngineStatus *string `json:"engine_status,omitempty"`
	JobId        *string `json:"job_id,omitempty"`
	Pattern      *string `json:"pattern,omitempty"`
	Reason       *string `json:"reason,omitempty"`
	Ts           *string `json:"ts,omitempty"`
	Type         string  `json:"type"`
}

// SSESimStarted defines model for SSESimStarted.
type SSESimStarted struct {
	Engine       *string `json:"engine,omitempty"`
	EngineStatus *string `json:"engine_status,omitempty"`
	JobId        *string `json:"job_id,omitempty"`
	Pattern      *string `json:"pattern,omitempty"`
	Ts           *string `json:"ts,omitempty"`
	Type         string  `json:"type"`
}

// AuthLoginJSONRequestBody defines body for AuthLogin for application/json ContentType.
type AuthLoginJSONRequestBody = LoginRequest

// AuthRegisterJSONRequestBody defines body for AuthRegister for application/json ContentType.
type AuthRegisterJSONRequestBody = RegisterRequest

// DiscoverFlashJSONRequestBody defines body for DiscoverFlash for application/json ContentType.
type DiscoverFlashJSONRequestBody = FlashRequest

// DiscoverOneClickJSONRequestBody defines body for DiscoverOneClick for application/json ContentType.
type DiscoverOneClickJSONRequestBody = OneClickRequest

// AsSSEPhaseProgress returns the union data inside the SSEEventEnvelope as a SSEPhaseProgress
func (t SSEEventEnvelope) AsSSEPhaseProgress() (SSEPhaseProgress, error) {
	var body SSEPhaseProgress
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSSEPhaseProgress overwrites any union data inside the SSEEventEnvelope as the provided SSEPhaseProgress
func (t *SSEEventEnvelope) FromSSEPhaseProgress(v SSEPhaseProgress) error {
	v.Type = "phase_progress"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSSEPhaseProgress performs a merge with any union data inside the SSEEventEnvelope, using the provided SSEPhaseProgress
func (t *SSEEventEnvelope) MergeSSEPhaseProgress(v SSEPhaseProgress) error {
	v.Type = "phase_progress"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSSESimStarted returns the union data inside the SSEEventEnvelope as a SSESimStarted
func (t SSEEventEnvelope) AsSSESimStarted() (SSESimStarted, error) {
	var body SSESimStarted
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSSESimStarted overwrites any union data inside the SSEEventEnvelope as the provided SSESimStarted
func (t *SSEEventEnvelope) FromSSESimStarted(v SSESimStarted) error {
	v.Type = "sim_started"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSSESimStarted performs a merge with any union data inside the SSEEventEnvelope, using the provided SSESimStarted
func (t *SSEEventEnvelope) MergeSSESimStarted(v SSESimStarted) error {
	v.Type = "sim_started"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSSESimFinished returns the union data inside the SSEEventEnvelope as a SSESimFinished
func (t SSEEventEnvelope) AsSSESimFinished() (SSESimFinished, error) {
	var body SSESimFinished
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSSESimFinished overwrites any union data inside the SSEEventEnvelope as the provided SSESimFinished
func (t *SSEEventEnvelope) FromSSESimFinished(v SSESimFinished) error {
	v.Type = "sim_finished"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSSESimFinished performs a merge with any union data inside the SSEEventEnvelope, using the provided SSESimFinished
func (t *SSEEventEnvelope) MergeSSESimFinished(v SSESimFinished) error {
	v.Type = "sim_finished"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSSESimSkipped returns the union data inside the SSEEventEnvelope as a SSESimSkipped
func (t SSEEventEnvelope) AsSSESimSkipped() (SSESimSkipped, error) {
	var body SSESimSkipped
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSSESimSkipped overwrites any union data inside the SSEEventEnvelope as the provided SSESimSkipped
func (t *SSEEventEnvelope) FromSSESimSkipped(v SSESimSkipped) error {
	v.Type = "sim_skipped"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSSESimSkipped performs a merge with any union data inside the SSEEventEnvelope, using the provided SSESimSkipped
func (t *SSEEventEnvelope) MergeSSESimSkipped(v SSESimSkipped) error {
	v.Type = "sim_skipped"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSSEComplete returns the union data inside the SSEEventEnvelope as a SSEComplete
func (t SSEEventEnvelope) AsSSEComplete() (SSEComplete, error) {
	var body SSEComplete
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSSEComplete overwrites any union data inside the SSEEventEnvelope as the provided SSEComplete
func (t *SSEEventEnvelope) FromSSEComplete(v SSEComplete) error {
	v.Type = "complete"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSSEComplete performs a merge with any union data inside the SSEEventEnvelope, using the provided SSEComplete
func (t *SSEEventEnvelope) MergeSSEComplete(v SSEComplete) error {
	v.Type = "complete"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSSEFailed returns the union data inside the SSEEventEnvelope as a SSEFailed
func (t SSEEventEnvelope) AsSSEFailed() (SSEFailed, error) {
	var body SSEFailed
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSSEFailed overwrites any union data inside the SSEEventEnvelope as the provided SSEFailed
func (t *SSEEventEnvelope) FromSSEFailed(v SSEFailed) error {
	v.Type = "failed"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSSEFailed performs a merge with any union data inside the SSEEventEnvelope, using the provided SSEFailed
func (t *SSEEventEnvelope) MergeSSEFailed(v SSEFailed) error {
	v.Type = "failed"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSSEError returns the union data inside the SSEEventEnvelope as a SSEError
func (t SSEEventEnvelope) AsSSEError() (SSEError, error) {
	var body SSEError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSSEError overwrites any union data inside the SSEEventEnvelope as the provided SSEError
func (t *SSEEventEnvelope) FromSSEError(v SSEError) error {
	v.Type = "error"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSSEError performs a merge with any union data inside the SSEEventEnvelope, using the provided SSEError
func (t *SSEEventEnvelope) MergeSSEError(v SSEError) error {
	v.Type = "error"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t SSEEventEnvelope) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t SSEEventEnvelope) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "complete":
		return t.AsSSEComplete()
	case "error":
		return t.AsSSEError()
	case "failed":
		return t.AsSSEFailed()
	case "phase_progress":
		return t.AsSSEPhaseProgress()
	case "sim_finished":
		return t.AsSSESimFinished()
	case "sim_skipped":
		return t.AsSSESimSkipped()
	case "sim_started":
		return t.AsSSESimStarted()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t SSEEventEnvelope) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *SSEEventEnvelope) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
