// Package i18n provides translation lookups for the TUI v9.
// Code generated by translate-pipeline/regen_i18n.py from .toml files. DO NOT EDIT.
package i18n

import (
	"bufio"
	"os"
	"regexp"
	"strings"
	"sync"
)

type Lang string

const (
	LangEN Lang = "en"
	LangRU Lang = "ru"
	LangZH Lang = "zh"
	LangJA Lang = "ja"
	LangDE Lang = "de"
	LangAR Lang = "ar"
	LangHI Lang = "hi"
)

var (
	currentLangMu sync.RWMutex
	currentLang   = LangEN
)

var translations = map[Lang]map[string]string{
	LangEN: {"app.lang": "EN", "app.model": "DeepSeek", "app.title": "C4REQBER v9", "card.code.t": "Simulation", "card.error.t": "Error", "card.hypothesis.t": "Hypothesis", "card.paper.t": "Paper", "card.phase.status": "in progress", "empty.hint": "Type a question above and press Enter", "empty.title": "Ready for your first discovery", "footer.cost": "$0.00", "footer.done": "COMPLETE", "footer.ready": "READY", "footer.running": "RUNNING", "keymap.cancel": "Cancel", "keymap.help": "Help", "keymap.quit": "Quit", "keymap.run": "Run", "phase.a": "Framing", "phase.b": "Knowledge acquisition", "phase.c": "Gap analysis", "phase.d": "Hypothesis generation", "phase.e": "Simulation", "phase.f": "Dissertation", "phase.g": "Quality control", "placeholder": "design a CRISPR guide RNA with minimal off-targets in T-cells", "toast.cancelled": "Cancelled", "toast.complete": "Discovery complete", "toast.empty": "Type a problem first", "toast.submit_failed": "Submit failed"},
	LangRU: {"app.lang": "RU", "app.model": "DeepSeek", "app.title": "C4REQBER v9", "card.code.t": "Симуляция", "card.error.t": "Ошибка", "card.hypothesis.t": "гипотеза", "card.paper.t": "Бумага", "card.phase.status": "в процессе", "empty.hint": "Введите вопрос выше и нажмите Enter.", "empty.title": "Готов к вашему первому открытию", "footer.cost": "$0.00", "footer.done": "Завершено", "footer.ready": "ГОТОВО", "footer.running": "Выполняется", "keymap.cancel": "Отмена", "keymap.help": "Помощь", "keymap.quit": "Отстань", "keymap.run": "Бегать", "phase.a": "Образование", "phase.b": "Приобретение знаний", "phase.c": "Обзор разрывов", "phase.d": "Генерация гипотез", "phase.e": "Симуляция", "phase.f": "Диссертация", "phase.g": "Контроль качества", "placeholder": "Разработать гибридный РНК-механизм CRISPR с минимальным количеством отрицательных последствий в Т-клетках.", "toast.cancelled": "Отменено", "toast.complete": "Завершено открытие", "toast.empty": "Сначала введите проблему.", "toast.submit_failed": "Подача не удалась"},
	LangZH: {"app.lang": "ZH", "app.model": "DeepSeek", "app.title": "C4REQBER v9", "card.code.t": "仿真", "card.error.t": "错误", "card.hypothesis.t": "假设", "card.paper.t": "论文", "card.phase.status": "进行中", "empty.hint": "在上方输入一个问题，然后按 Enter。", "empty.title": "准备好迎接你的第一次探索", "footer.cost": "$0.00", "footer.done": "完成", "footer.ready": "就绪", "footer.running": "运行中", "keymap.cancel": "取消", "keymap.help": "帮助", "keymap.quit": "停止", "keymap.run": "运行", "phase.a": "框架", "phase.b": "知识获取", "phase.c": "差距分析", "phase.d": "假设生成", "phase.e": "仿真", "phase.f": "论文", "phase.g": "质量控制", "placeholder": "设计一种CRISPR引导RNA，使其在T细胞中产生最少的脱靶效应。", "toast.cancelled": "已取消", "toast.complete": "发现完成", "toast.empty": "首先输入一个问题", "toast.submit_failed": "提交失败"},
	LangJA: {"app.lang": "JA", "app.model": "DeepSeek", "app.title": "C4REQBER v9", "card.code.t": "シミュレーション", "card.error.t": "エラー", "card.hypothesis.t": "仮説", "card.paper.t": "論文", "card.phase.status": "進行中", "empty.hint": "上記に質問を入力し、Enterキーを押してください。", "empty.title": "初回の発見に向けて準備ができています。", "footer.cost": "$0.00", "footer.done": "完了", "footer.ready": "準備完了", "footer.running": "実行中", "keymap.cancel": "キャンセル", "keymap.help": "助けてください", "keymap.quit": "辞める", "keymap.run": "実行する", "phase.a": "枠組み化", "phase.b": "知識獲得", "phase.c": "ギャップ分析", "phase.d": "仮説生成", "phase.e": "シミュレーション", "phase.f": "論文", "phase.g": "品質管理", "placeholder": "CRISPRガイドRNAを設計し、T細胞におけるオフターゲットの発生を最小限に抑える", "toast.cancelled": "キャンセルされた", "toast.complete": "発見完了", "toast.empty": "まず、問題を入力してください。", "toast.submit_failed": "提出失敗"},
	LangDE: {"app.lang": "DE", "app.model": "DeepSeek", "app.title": "C4REQBER v9", "card.code.t": "Simulation", "card.error.t": "Fehler", "card.hypothesis.t": "Hypothese", "card.paper.t": "Papier", "card.phase.status": "in Bearbeitung", "empty.hint": "Typen Sie eine Frage und drücken Sie Enter.", "empty.title": "Bereit für Ihre erste Entdeckung", "footer.cost": "0,00 $", "footer.done": "Fertig", "footer.ready": "Bereit", "footer.running": "Läuft", "keymap.cancel": "Stornieren", "keymap.help": "Hilfe", "keymap.quit": "Beenden", "keymap.run": "Laufen", "phase.a": "Framing", "phase.b": "Wissenserwerb", "phase.c": "Lückeanalyse", "phase.d": "Hypothesengenerierung", "phase.e": "Simulation", "phase.f": "Dissertation", "phase.g": "Qualitätskontrolle", "placeholder": "Entwickeln Sie ein CRISPR-Guide-RNA mit minimalen Off-Target-Effekten in T-Zellen.", "toast.cancelled": "Abgebrochen", "toast.complete": "Abgeschlossen", "toast.empty": "Führen Sie zuerst ein Problem ein.", "toast.submit_failed": "Übermittlung fehlgeschlagen"},
	LangAR: {"app.lang": "AR", "app.model": "DeepSeek", "app.title": "C4REQBER v9", "card.code.t": "محاكاة", "card.error.t": "خطأ", "card.hypothesis.t": "فرضية", "card.paper.t": "ورقة", "card.phase.status": "في طور التنفيذ", "empty.hint": "أدخل سؤالًا أعلاه واضغط على Enter.", "empty.title": "جاهز لآخر اكتشافاتك", "footer.cost": "0.00 دولار", "footer.done": "مكتمل", "footer.ready": "جاهز", "footer.running": "قيد التشغيل", "keymap.cancel": "إلغاء", "keymap.help": "مساعدة", "keymap.quit": "توقف", "keymap.run": "تشغيل/الهروب", "phase.a": "تحديد الإطار", "phase.b": "اكتساب المعرفة", "phase.c": "تحليل الفجوة", "phase.d": "توليد الفرضيات", "phase.e": "محاكاة", "phase.f": "أطروحة", "phase.g": "مراقبة الجودة", "placeholder": "تصميم جينوم RNA توجيهي باستخدام تقنية CRISPR بأقل قدر ممكن من التأثيرات خارج الهدف في الخلايا التائية.", "toast.cancelled": "ملغى", "toast.complete": "اكتشاف مكتمل", "toast.empty": "أدخل مشكلة أولاً", "toast.submit_failed": "الإرسال فشل"},
	LangHI: {"app.lang": "HI", "app.model": "DeepSeek", "app.title": "C4REQBER v9", "card.code.t": "सिमुलेशन", "card.error.t": "त्रुटि", "card.hypothesis.t": "परिकल्पना", "card.paper.t": "कागज़/पेपर", "card.phase.status": "चल रहा है", "empty.hint": "कृपया ऊपर एक प्रश्न लिखें और Enter दबाएं।", "empty.title": "पहली खोज के लिए तैयार", "footer.cost": "0.00 डॉलर", "footer.done": "पूर्ण", "footer.ready": "तैयार", "footer.running": "चल रहा है", "keymap.cancel": "रद्द करें", "keymap.help": "सहायता करें", "keymap.quit": "काम छोड़ दें", "keymap.run": "चलो", "phase.a": "फ्रेमिंग", "phase.b": "ज्ञान अधिग्रहण", "phase.c": "अंतर विश्लेषण", "phase.d": "परिकल्पना निर्माण", "phase.e": "सिमुलेशन", "phase.f": "शोधपत्र/अनुसंधान", "phase.g": "गुणवत्ता नियंत्रण", "placeholder": "CRISPR गाइड आरएनए को डिज़ाइन करें, जिसमें टी-कोशिकाओं में कम से कम ऑफ-टार्गेट्स हों।", "toast.cancelled": "रद्द", "toast.complete": "खोज पूर्ण", "toast.empty": "सबसे पहले एक समस्या लिखें।", "toast.submit_failed": "प्रस्तुति विफल रही"},
}

func SetLang(l Lang) {
	currentLangMu.Lock()
	defer currentLangMu.Unlock()
	currentLang = l
}

func GetLang() Lang {
	currentLangMu.RLock()
	defer currentLangMu.RUnlock()
	return currentLang
}

func Translations() map[Lang]map[string]string {
	cp := make(map[Lang]map[string]string, len(translations))
	for k, v := range translations {
		inner := make(map[string]string, len(v))
		for ik, iv := range v {
			inner[ik] = iv
		}
	cp[k] = inner
	}
	return cp
}

// T returns the translation for key in the current language, or the key itself if missing.
func T(key string) string {
	currentLangMu.RLock()
	lang := currentLang
	currentLangMu.RUnlock()
	return TFor(key, lang)
}

// TFor returns the translation for key in the specified language,
// falling back to English, then to the key itself.
func TFor(key string, lang Lang) string {
	currentLangMu.RLock()
	defer currentLangMu.RUnlock()
	if val, ok := translations[lang][key]; ok {
		return val
	}
	if val, ok := translations[LangEN][key]; ok {
		return val
	}
	return key
}

// SetTranslations overrides translations for a given language.
func SetTranslations(lang Lang, m map[string]string) {
	currentLangMu.Lock()
	defer currentLangMu.Unlock()
	if m == nil {
		return
	}
	translations[lang] = m
}

// LoadLangFromToml loads translations from a TOML file.
func LoadLangFromToml(path string, lang Lang) error {
	f, err := os.Open(path)
	if err != nil {
		return err
	}
	defer f.Close()
	m := translations[lang]
	if m == nil {
		m = map[string]string{}
		translations[lang] = m
	}
	scanner := bufio.NewScanner(f)
	keyRe := regexp.MustCompile(`^([a-z0-9_.]+)\s*=\s*"([^"]*)"\s*$`)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		matches := keyRe.FindStringSubmatch(line)
		if len(matches) == 3 {
			m[matches[1]] = matches[2]
		}
	}
	return scanner.Err()
}