"""C4REQBER: Agent Mode v4.1 — Core Agent
Autonomous scientific discovery agent
"""
from __future__ import annotations


__all__ = [
    "AgentHypothesis",
    "AgentReport",
    "ScientificDiscoveryAgent",
    "get_agent",
]

import asyncio
import json
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Optional

from rich.console import Console
from rich.progress import BarColumn, Progress, SpinnerColumn, TextColumn

from src.analogy import AnalogyResult, get_analogy_engine
from src.graph.knowledge_graph import get_knowledge_graph
from src.triz import get_c4_triz_bridge_obj
from src.validation import FalsifiabilityCriterion, get_validation_tracker


console = Console()


@dataclass
class AgentHypothesis:
    """A hypothesis generated by the agent."""

    id: str
    problem: str
    hypothesis: str
    mechanism: str
    c4_path: list[str]
    triz_principles: list[int]
    analogies: list[AnalogyResult]
    confidence: float
    falsifiability_criteria: list[FalsifiabilityCriterion]
    estimated_validation_cost: float  # USD
    estimated_time_to_validate: str  # e.g., "2 weeks"
    domain: str
    generation_method: str  # "c4", "analogy", "triz", "hybrid"


@dataclass
class AgentReport:
    """Full report from agent execution."""

    query: str
    start_time: datetime
    end_time: datetime
    total_hypotheses: int
    hypotheses: list[AgentHypothesis]
    rankings: dict[str, list[str]]  # By confidence, cost, speed
    summary: str
    recommendations: list[str]


class ScientificDiscoveryAgent:
    """
    Autonomous agent for scientific discovery.

    Combines C4, TRIZ, and Analogy methods to generate
    and rank hypotheses without user intervention.
    """

    def __init__(self) -> None:
        self.kg = get_knowledge_graph()
        self.analogy = get_analogy_engine()
        self.triz = get_c4_triz_bridge_obj()
        self.validator = get_validation_tracker()
        self._hypothesis_counter = 0

    async def discover(
        self,
        problem: str,
        time_budget: str | None = None,
        max_hypotheses: int = 10,
        domains: list[str] | None = None,
    ) -> AgentReport:
        """
        Autonomous discovery process.

        Args:
            problem: Natural language problem description
            time_budget: e.g., "1h", "30m" (for progress reporting)
            max_hypotheses: Maximum number to generate
            domains: Domains to explore (auto-detected if None)

        Returns:
            AgentReport with hypotheses and recommendations
        """
        from .strategies import (
            _estimate_cost,
            _estimate_time,
            _generate_analogies,
            _generate_c4_triz,
            _generate_falsifiability,
            _generate_hybrid,
            _generate_recommendations,
            _generate_summary,
            _parse_time,
            _rank_hypotheses,
        )

        start_time = datetime.now()

        console.print("[bold blue]🔬 Scientific Discovery Agent[/bold blue]")
        console.print(f"Problem: {problem}")
        console.print(f"Max hypotheses: {max_hypotheses}\n")

        hypotheses: list[AgentHypothesis] = []

        with Progress(
            SpinnerColumn(),
            TextColumn("[progress.description]{task.description}"),
            BarColumn(),
            TextColumn("[progress.percentage]{task.percentage:>3.0f}%"),
            console=console,
        ) as progress:
            # Step 1: Analyze problem
            task1 = progress.add_task("[cyan]Analyzing problem...", total=100)
            detected_domains = domains or self._detect_domains(problem)
            progress.update(task1, completed=100)

            # Step 2: Generate via C4+TRIZ
            task2 = progress.add_task("[cyan]Generating via C4+TRIZ...", total=100)
            c4_hypotheses = await _generate_c4_triz(self, problem, detected_domains)
            hypotheses.extend(c4_hypotheses)
            progress.update(task2, completed=100)

            # Step 3: Generate via Analogy
            task3 = progress.add_task(
                "[cyan]Exploring cross-domain analogies...", total=100
            )
            analogy_hypotheses = await _generate_analogies(
                self, problem, detected_domains
            )
            hypotheses.extend(analogy_hypotheses)
            progress.update(task3, completed=100)

            # Step 4: Generate via Hybrid
            task4 = progress.add_task("[cyan]Creating hybrid solutions...", total=100)
            hybrid_hypotheses = await _generate_hybrid(self, hypotheses)
            hypotheses.extend(hybrid_hypotheses)
            progress.update(task4, completed=100)

            # Step 5: Evaluate falsifiability
            task5 = progress.add_task(
                "[cyan]Evaluating falsifiability...", total=len(hypotheses)
            )
            for h in hypotheses:
                h.falsifiability_criteria = await _generate_falsifiability(self, h)
                progress.advance(task5)

            # Step 6: Rank and filter
            task6 = progress.add_task("[cyan]Ranking hypotheses...", total=100)
            hypotheses = _rank_hypotheses(hypotheses)[:max_hypotheses]
            progress.update(task6, completed=100)

            # Step 7: Estimate costs
            task7 = progress.add_task(
                "[cyan]Estimating validation costs...", total=len(hypotheses)
            )
            for h in hypotheses:
                h.estimated_validation_cost = _estimate_cost(h)
                h.estimated_time_to_validate = _estimate_time(h)
                progress.advance(task7)

        end_time = datetime.now()

        # Generate rankings
        rankings = {
            "by_confidence": [
                h.id
                for h in sorted(hypotheses, key=lambda x: x.confidence, reverse=True)
            ],
            "by_cost": [
                h.id
                for h in sorted(hypotheses, key=lambda x: x.estimated_validation_cost)
            ],
            "by_speed": [
                h.id
                for h in sorted(
                    hypotheses,
                    key=lambda x: _parse_time(x.estimated_time_to_validate),
                )
            ],
        }

        # Generate report
        report = AgentReport(
            query=problem,
            start_time=start_time,
            end_time=end_time,
            total_hypotheses=len(hypotheses),
            hypotheses=hypotheses,
            rankings=rankings,
            summary=_generate_summary(hypotheses),
            recommendations=_generate_recommendations(hypotheses),
        )

        return report

    def _detect_domains(self, problem: str) -> list[str]:
        """Auto-detect relevant domains from problem description."""
        keywords = {
            "battery": ["energy", "chemistry", "materials"],
            "software": ["computer_science", "mathematics"],
            "biological": ["biology", "chemistry"],
            "mechanical": ["physics", "engineering"],
            "economic": ["economics", "mathematics"],
            "algorithm": ["computer_science", "mathematics"],
            "protein": ["biology", "chemistry"],
            "neural": ["biology", "computer_science"],
        }

        problem_lower = problem.lower()
        detected = set()

        for keyword, domains in keywords.items():
            if keyword in problem_lower:
                detected.update(domains)

        return list(detected) if detected else ["general"]

    def export_report(self, report: AgentReport, output_path: str) -> None:
        """Export report to file (Markdown or JSON)."""
        path = Path(output_path)

        if path.suffix == ".json":
            # JSON export
            data = {
                "query": report.query,
                "duration_seconds": (
                    report.end_time - report.start_time
                ).total_seconds(),
                "total_hypotheses": report.total_hypotheses,
                "summary": report.summary,
                "recommendations": report.recommendations,
                "hypotheses": [
                    {
                        "id": h.id,
                        "hypothesis": h.hypothesis,
                        "confidence": h.confidence,
                        "method": h.generation_method,
                        "c4_path": h.c4_path,
                        "triz_principles": h.triz_principles,
                        "validation_cost": h.estimated_validation_cost,
                        "validation_time": h.estimated_time_to_validate,
                    }
                    for h in report.hypotheses
                ],
            }
            with open(path, "w") as f:
                json.dump(data, f, indent=2)

        else:
            # Markdown export
            md = f"""# Scientific Discovery Report

**Query:** {report.query}
**Generated:** {report.start_time.strftime("%Y-%m-%d %H:%M")}
**Duration:** {(report.end_time - report.start_time).total_seconds() / 60:.1f} minutes

## Summary

{report.summary}

## Top Recommendations

"""
            for i, rec in enumerate(report.recommendations, 1):
                md += f"{i}. {rec}\n"

            md += "\n## Hypotheses\n\n"

            for h in report.hypotheses:
                md += f"""### {h.id} (Confidence: {h.confidence:.1%})

**Hypothesis:** {h.hypothesis}

**Mechanism:** {h.mechanism}

**Method:** {h.generation_method}

**C4 Path:** {" → ".join(h.c4_path)}

**TRIZ Principles:** {", ".join(map(str, h.triz_principles))}

**Validation:**
- Estimated cost: ${h.estimated_validation_cost:,.0f}
- Estimated time: {h.estimated_time_to_validate}

---

"""

            with open(path, "w") as f:
                f.write(md)

        console.print(f"[green]✓ Report exported to {output_path}[/green]")


# ═══════════════════════════════════════════════════════════════════
# SINGLETON INSTANCE (backed by DI container)
# ═══════════════════════════════════════════════════════════════════

def get_agent() -> ScientificDiscoveryAgent:
    """Get singleton agent instance (backed by DI container)."""
    from src.di.container import get_container
    return get_container().get_or_register("scientific_discovery_agent", ScientificDiscoveryAgent)
