"""
C4REQBER: Analogy Data
Domain concepts and conceptual metaphors.
"""
from __future__ import annotations


DOMAIN_CONCEPTS: dict[str, list[str]] = {
    "biology": [
        "cell", "organism", "evolution", "ecosystem", "gene", "protein",
        "metabolism", "neuron", "immune system", "homeostasis", "DNA",
        "photosynthesis", "mitochondria", "enzyme", "hormone", "tissue",
        "organ", "population", "species", "adaptation", "selection",
        "symbiosis", "predator", "prey", "parasite", "host", "virus",
        "bacteria", "fungi", "plant", "animal", "human", "brain", "heart",
        "blood", "muscle", "bone", "skin", "eye", "ear",
    ],
    "physics": [
        "force", "energy", "field", "wave", "particle", "entropy",
        "equilibrium", "resonance", "oscillation", "potential", "mass",
        "velocity", "acceleration", "momentum", "gravity", "electromagnetism",
        "quantum", "relativity", "thermodynamics", "pressure", "temperature",
        "volume", "density", "viscosity", "friction", "tension", "compression",
        "torque", "inertia", "light", "sound", "heat", "electricity",
        "magnetism", "atom", "molecule", "electron", "proton", "neutron", "quark",
    ],
    "computer_science": [
        "algorithm", "data structure", "network", "memory", "processor",
        "protocol", "interface", "queue", "stack", "recursion",
        "machine learning", "artificial intelligence", "neural network",
        "database", "cloud computing", "distributed system", "API", "function",
        "variable", "loop", "condition", "class", "object", "inheritance",
        "polymorphism", "encapsulation", "abstraction", "compiler",
        "interpreter", "operating system", "kernel", "security", "encryption",
        "hash", "blockchain", "container",
    ],
    "energy": [
        "battery", "solar panel", "wind turbine", "power plant", "electricity",
        "renewable energy", "fossil fuel", "nuclear", "energy storage", "grid",
        "transmission", "efficiency", "charging", "discharging", "capacity",
        "voltage", "current", "resistance", "power", "watt", "kilowatt",
        "megawatt", "photovoltaic", "thermal", "kinetic", "potential energy",
        "chemical energy", "nuclear energy", "fusion", "fission",
    ],
    "materials": [
        "metal", "polymer", "ceramic", "composite", "alloy", "semiconductor",
        "superconductor", "insulator", "conductor", "crystal", "amorphous",
        "nanomaterial", "graphene", "carbon fiber", "strength", "hardness",
        "ductility", "elasticity", "plasticity", "corrosion", "oxidation",
        "reduction", "catalysis", "synthesis",
    ],
    "mathematics": [
        "number", "equation", "function", "variable", "constant", "vector",
        "matrix", "tensor", "calculus", "algebra", "geometry", "topology",
        "statistics", "probability", "derivative", "integral",
        "differential equation", "linear algebra", "group theory", "set theory",
        "logic",
    ],
    "general": [
        "system", "process", "structure", "function", "behavior", "pattern",
        "relationship", "interaction", "feedback", "control", "optimization",
        "efficiency", "performance", "reliability", "complexity", "simplicity",
        "flexibility", "robustness",
    ],
    "economics": [
        "market", "supply", "demand", "equilibrium", "inflation", "investment",
        "liquidity", "risk", "portfolio", "bubble",
    ],
    "chemistry": [
        "molecule", "reaction", "catalyst", "bond", "solution", "equilibrium",
        "concentration", "diffusion", "precipitation",
    ],
}

CONCEPTUAL_METAPHORS: list[tuple[str, str, str, str]] = [
    # Biology <-> Computer Science
    ("biology", "neuron", "computer_science", "node"),
    ("biology", "neural network", "computer_science", "artificial neural network"),
    ("biology", "evolution", "computer_science", "genetic algorithm"),
    ("biology", "immune system", "computer_science", "intrusion detection"),
    ("biology", "DNA", "computer_science", "code"),
    ("biology", "gene", "computer_science", "instruction"),
    ("biology", "cell", "computer_science", "unit"),
    ("biology", "tissue", "computer_science", "module"),
    ("biology", "organ", "computer_science", "component"),
    ("biology", "brain", "computer_science", "processor"),
    ("biology", "photosynthesis", "computer_science", "energy harvesting"),
    # Biology <-> Economics
    ("biology", "metabolism", "economics", "cash flow"),
    ("biology", "ecosystem", "economics", "market"),
    ("biology", "cell", "society", "individual"),
    ("biology", "population", "economics", "workforce"),
    ("biology", "predator", "economics", "competitor"),
    ("biology", "prey", "economics", "customer"),
    ("biology", "symbiosis", "economics", "partnership"),
    ("biology", "adaptation", "economics", "innovation"),
    ("biology", "selection", "economics", "competition"),
    ("biology", "homeostasis", "economics", "market equilibrium"),
    # Physics <-> Economics / Sociology
    ("physics", "force", "economics", "incentive"),
    ("physics", "potential energy", "economics", "potential profit"),
    ("physics", "kinetic energy", "economics", "active revenue"),
    ("physics", "entropy", "information_theory", "information_entropy"),
    ("physics", "resonance", "sociology", "viral phenomenon"),
    ("physics", "wave", "sociology", "trend"),
    ("physics", "equilibrium", "economics", "market equilibrium"),
    ("physics", "friction", "economics", "transaction cost"),
    ("physics", "inertia", "economics", "market resistance"),
    ("physics", "momentum", "economics", "market trend"),
    ("physics", "pressure", "economics", "market pressure"),
    ("physics", "temperature", "economics", "market heat"),
    # Physics <-> Energy
    ("physics", "potential", "energy", "storage capacity"),
    ("physics", "flow", "energy", "current"),
    ("physics", "resistance", "energy", "internal resistance"),
    ("physics", "capacitor", "energy", "battery"),
    ("physics", "inductor", "energy", "flywheel"),
    # Chemistry <-> Economics / Society
    ("chemistry", "catalyst", "economics", "accelerator"),
    ("chemistry", "reaction", "sociology", "social change"),
    ("chemistry", "equilibrium", "economics", "market equilibrium"),
    ("chemistry", "bond", "society", "relationship"),
    ("chemistry", "solution", "society", "resolution"),
    ("chemistry", "compound", "society", "organization"),
    ("chemistry", "crystal", "society", "structure"),
    # Computer Science <-> Biology / Energy
    ("computer_science", "algorithm", "biology", "metabolic pathway"),
    ("computer_science", "memory", "biology", "memory"),
    ("computer_science", "protocol", "sociology", "ritual"),
    ("computer_science", "virus", "biology", "virus"),
    ("computer_science", "firewall", "biology", "immune system"),
    ("computer_science", "cache", "biology", "short-term memory"),
    ("computer_science", "database", "biology", "long-term memory"),
    ("computer_science", "network", "biology", "nervous system"),
    ("computer_science", "bandwidth", "biology", "nerve capacity"),
    ("computer_science", "load balancing", "energy", "grid management"),
    ("computer_science", "queue", "energy", "storage buffer"),
    ("computer_science", "scheduler", "energy", "load dispatcher"),
    ("computer_science", "optimization", "energy", "efficiency tuning"),
    # Mathematics <-> All domains
    ("mathematics", "optimization", "energy", "efficiency maximization"),
    ("mathematics", "gradient", "economics", "marginal change"),
    ("mathematics", "convergence", "physics", "equilibrium"),
    ("mathematics", "divergence", "physics", "instability"),
    ("mathematics", "graph", "computer_science", "network"),
    ("mathematics", "graph", "biology", "food web"),
    # Materials <-> Energy
    ("materials", "conductor", "energy", "electrode"),
    ("materials", "insulator", "energy", "separator"),
    ("materials", "crystal", "energy", "lattice structure"),
    ("materials", "composite", "energy", "hybrid system"),
    ("materials", "fatigue", "energy", "degradation"),
    ("materials", "corrosion", "energy", "electrolyte breakdown"),
    # Energy <-> Biology
    ("energy", "storage", "biology", "fat storage"),
    ("energy", "grid", "biology", "circulatory system"),
    ("energy", "peak load", "biology", "stress response"),
    ("energy", "baseload", "biology", "metabolic rate"),
    ("energy", "renewable", "biology", "sustainable resource"),
]
