// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package oapi

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// Defines values for OneClickRequestLlmTier.
const (
	C1    OneClickRequestLlmTier = "C1"
	C2    OneClickRequestLlmTier = "C2"
	C3    OneClickRequestLlmTier = "C3"
	Empty OneClickRequestLlmTier = ""
)

// Valid indicates whether the value is a known member of the OneClickRequestLlmTier enum.
func (e OneClickRequestLlmTier) Valid() bool {
	switch e {
	case C1:
		return true
	case C2:
		return true
	case C3:
		return true
	case Empty:
		return true
	default:
		return false
	}
}

// Defines values for OneClickRequestOutputMode.
const (
	Explain OneClickRequestOutputMode = "explain"
	Human   OneClickRequestOutputMode = "human"
)

// Valid indicates whether the value is a known member of the OneClickRequestOutputMode enum.
func (e OneClickRequestOutputMode) Valid() bool {
	switch e {
	case Explain:
		return true
	case Human:
		return true
	default:
		return false
	}
}

// FlashRequest defines model for FlashRequest.
type FlashRequest struct {
	Domain  *string `json:"domain,omitempty"`
	Problem string  `json:"problem"`
}

// FlexibleObject defines model for FlexibleObject.
type FlexibleObject map[string]interface{}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status  *string `json:"status,omitempty"`
	Version *string `json:"version,omitempty"`
}

// JobCreatedResponse defines model for JobCreatedResponse.
type JobCreatedResponse struct {
	JobId  string `json:"job_id"`
	Status string `json:"status"`
}

// JobStatusResponse defines model for JobStatusResponse.
type JobStatusResponse struct {
	Errors      *[]string               `json:"errors,omitempty"`
	JobId       *string                 `json:"job_id,omitempty"`
	Phase       *string                 `json:"phase,omitempty"`
	PhaseDetail *string                 `json:"phase_detail,omitempty"`
	Progress    *float32                `json:"progress,omitempty"`
	Result      *map[string]interface{} `json:"result,omitempty"`
	Status      *string                 `json:"status,omitempty"`
}

// KnowledgeSearchRequest defines model for KnowledgeSearchRequest.
type KnowledgeSearchRequest struct {
	MaxResults *int   `json:"max_results,omitempty"`
	Query      string `json:"query"`
}

// KnowledgeSearchResponse defines model for KnowledgeSearchResponse.
type KnowledgeSearchResponse struct {
	Query       *string           `json:"query,omitempty"`
	Results     *[]FlexibleObject `json:"results,omitempty"`
	SourcesUsed *[]string         `json:"sources_used,omitempty"`
	Total       *int              `json:"total,omitempty"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string  `json:"email"`
	Name     *string `json:"name,omitempty"`
	Password string  `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	AccessToken *string `json:"access_token,omitempty"`
	TokenType   *string `json:"token_type,omitempty"`
}

// MultiRequest defines model for MultiRequest.
type MultiRequest struct {
	Count   *int    `json:"count,omitempty"`
	Domain  *string `json:"domain,omitempty"`
	Problem string  `json:"problem"`
}

// OneClickRequest defines model for OneClickRequest.
type OneClickRequest struct {
	Domain     *string                    `json:"domain,omitempty"`
	LlmTier    *OneClickRequestLlmTier    `json:"llm_tier,omitempty"`
	OutputMode *OneClickRequestOutputMode `json:"output_mode,omitempty"`
	Problem    string                     `json:"problem"`
}

// OneClickRequestLlmTier defines model for OneClickRequest.LlmTier.
type OneClickRequestLlmTier string

// OneClickRequestOutputMode defines model for OneClickRequest.OutputMode.
type OneClickRequestOutputMode string

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    string  `json:"email"`
	Name     *string `json:"name,omitempty"`
	Password string  `json:"password"`
}

// SSEBase defines model for SSEBase.
type SSEBase struct {
	JobId *string `json:"job_id,omitempty"`
	Ts    *string `json:"ts,omitempty"`
	Type  string  `json:"type"`
}

// SSEComplete defines model for SSEComplete.
type SSEComplete struct {
	Errors   *[]string               `json:"errors,omitempty"`
	JobId    *string                 `json:"job_id,omitempty"`
	Phase    *string                 `json:"phase,omitempty"`
	Progress *float32                `json:"progress,omitempty"`
	Result   *map[string]interface{} `json:"result,omitempty"`
	Status   *string                 `json:"status,omitempty"`
	Ts       *string                 `json:"ts,omitempty"`
	Type     string                  `json:"type"`
}

// SSEError defines model for SSEError.
type SSEError struct {
	Detail *string `json:"detail,omitempty"`
	JobId  *string `json:"job_id,omitempty"`
	Ts     *string `json:"ts,omitempty"`
	Type   string  `json:"type"`
}

// SSEEventEnvelope JSON payload inside SSE data lines
type SSEEventEnvelope struct {
	union json.RawMessage
}

// SSEFailed defines model for SSEFailed.
type SSEFailed struct {
	Errors   *[]string `json:"errors,omitempty"`
	JobId    *string   `json:"job_id,omitempty"`
	Phase    *string   `json:"phase,omitempty"`
	Progress *float32  `json:"progress,omitempty"`
	Status   *string   `json:"status,omitempty"`
	Ts       *string   `json:"ts,omitempty"`
	Type     string    `json:"type"`
}

// SSEPhaseProgress defines model for SSEPhaseProgress.
type SSEPhaseProgress struct {
	Detail   *string  `json:"detail,omitempty"`
	JobId    *string  `json:"job_id,omitempty"`
	Phase    *string  `json:"phase,omitempty"`
	Progress *float32 `json:"progress,omitempty"`
	Status   *string  `json:"status,omitempty"`
	Ts       *string  `json:"ts,omitempty"`
	Type     string   `json:"type"`
}

// SSESimFinished defines model for SSESimFinished.
type SSESimFinished struct {
	Engine       *string `json:"engine,omitempty"`
	EngineStatus *string `json:"engine_status,omitempty"`
	JobId        *string `json:"job_id,omitempty"`
	Pattern      *string `json:"pattern,omitempty"`
	Ts           *string `json:"ts,omitempty"`
	Type         string  `json:"type"`
	Verdict      *string `json:"verdict,omitempty"`
}

// SSESimSkipped defines model for SSESimSkipped.
type SSESimSkipped struct {
	Engine       *string `json:"engine,omitempty"`
	EngineStatus *string `json:"engine_status,omitempty"`
	JobId        *string `json:"job_id,omitempty"`
	Pattern      *string `json:"pattern,omitempty"`
	Reason       *string `json:"reason,omitempty"`
	Ts           *string `json:"ts,omitempty"`
	Type         string  `json:"type"`
}

// SSESimStarted defines model for SSESimStarted.
type SSESimStarted struct {
	Engine       *string `json:"engine,omitempty"`
	EngineStatus *string `json:"engine_status,omitempty"`
	JobId        *string `json:"job_id,omitempty"`
	Pattern      *string `json:"pattern,omitempty"`
	Ts           *string `json:"ts,omitempty"`
	Type         string  `json:"type"`
}

// AuthLoginJSONRequestBody defines body for AuthLogin for application/json ContentType.
type AuthLoginJSONRequestBody = LoginRequest

// AuthRegisterJSONRequestBody defines body for AuthRegister for application/json ContentType.
type AuthRegisterJSONRequestBody = RegisterRequest

// DiscoverFlashJSONRequestBody defines body for DiscoverFlash for application/json ContentType.
type DiscoverFlashJSONRequestBody = FlashRequest

// DiscoverMultiJSONRequestBody defines body for DiscoverMulti for application/json ContentType.
type DiscoverMultiJSONRequestBody = MultiRequest

// DiscoverOneClickJSONRequestBody defines body for DiscoverOneClick for application/json ContentType.
type DiscoverOneClickJSONRequestBody = OneClickRequest

// KnowledgeSearchJSONRequestBody defines body for KnowledgeSearch for application/json ContentType.
type KnowledgeSearchJSONRequestBody = KnowledgeSearchRequest

// AsSSEPhaseProgress returns the union data inside the SSEEventEnvelope as a SSEPhaseProgress
func (t SSEEventEnvelope) AsSSEPhaseProgress() (SSEPhaseProgress, error) {
	var body SSEPhaseProgress
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSSEPhaseProgress overwrites any union data inside the SSEEventEnvelope as the provided SSEPhaseProgress
func (t *SSEEventEnvelope) FromSSEPhaseProgress(v SSEPhaseProgress) error {
	v.Type = "phase_progress"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSSEPhaseProgress performs a merge with any union data inside the SSEEventEnvelope, using the provided SSEPhaseProgress
func (t *SSEEventEnvelope) MergeSSEPhaseProgress(v SSEPhaseProgress) error {
	v.Type = "phase_progress"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSSESimStarted returns the union data inside the SSEEventEnvelope as a SSESimStarted
func (t SSEEventEnvelope) AsSSESimStarted() (SSESimStarted, error) {
	var body SSESimStarted
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSSESimStarted overwrites any union data inside the SSEEventEnvelope as the provided SSESimStarted
func (t *SSEEventEnvelope) FromSSESimStarted(v SSESimStarted) error {
	v.Type = "sim_started"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSSESimStarted performs a merge with any union data inside the SSEEventEnvelope, using the provided SSESimStarted
func (t *SSEEventEnvelope) MergeSSESimStarted(v SSESimStarted) error {
	v.Type = "sim_started"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSSESimFinished returns the union data inside the SSEEventEnvelope as a SSESimFinished
func (t SSEEventEnvelope) AsSSESimFinished() (SSESimFinished, error) {
	var body SSESimFinished
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSSESimFinished overwrites any union data inside the SSEEventEnvelope as the provided SSESimFinished
func (t *SSEEventEnvelope) FromSSESimFinished(v SSESimFinished) error {
	v.Type = "sim_finished"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSSESimFinished performs a merge with any union data inside the SSEEventEnvelope, using the provided SSESimFinished
func (t *SSEEventEnvelope) MergeSSESimFinished(v SSESimFinished) error {
	v.Type = "sim_finished"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSSESimSkipped returns the union data inside the SSEEventEnvelope as a SSESimSkipped
func (t SSEEventEnvelope) AsSSESimSkipped() (SSESimSkipped, error) {
	var body SSESimSkipped
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSSESimSkipped overwrites any union data inside the SSEEventEnvelope as the provided SSESimSkipped
func (t *SSEEventEnvelope) FromSSESimSkipped(v SSESimSkipped) error {
	v.Type = "sim_skipped"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSSESimSkipped performs a merge with any union data inside the SSEEventEnvelope, using the provided SSESimSkipped
func (t *SSEEventEnvelope) MergeSSESimSkipped(v SSESimSkipped) error {
	v.Type = "sim_skipped"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSSEComplete returns the union data inside the SSEEventEnvelope as a SSEComplete
func (t SSEEventEnvelope) AsSSEComplete() (SSEComplete, error) {
	var body SSEComplete
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSSEComplete overwrites any union data inside the SSEEventEnvelope as the provided SSEComplete
func (t *SSEEventEnvelope) FromSSEComplete(v SSEComplete) error {
	v.Type = "complete"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSSEComplete performs a merge with any union data inside the SSEEventEnvelope, using the provided SSEComplete
func (t *SSEEventEnvelope) MergeSSEComplete(v SSEComplete) error {
	v.Type = "complete"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSSEFailed returns the union data inside the SSEEventEnvelope as a SSEFailed
func (t SSEEventEnvelope) AsSSEFailed() (SSEFailed, error) {
	var body SSEFailed
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSSEFailed overwrites any union data inside the SSEEventEnvelope as the provided SSEFailed
func (t *SSEEventEnvelope) FromSSEFailed(v SSEFailed) error {
	v.Type = "failed"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSSEFailed performs a merge with any union data inside the SSEEventEnvelope, using the provided SSEFailed
func (t *SSEEventEnvelope) MergeSSEFailed(v SSEFailed) error {
	v.Type = "failed"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSSEError returns the union data inside the SSEEventEnvelope as a SSEError
func (t SSEEventEnvelope) AsSSEError() (SSEError, error) {
	var body SSEError
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSSEError overwrites any union data inside the SSEEventEnvelope as the provided SSEError
func (t *SSEEventEnvelope) FromSSEError(v SSEError) error {
	v.Type = "error"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSSEError performs a merge with any union data inside the SSEEventEnvelope, using the provided SSEError
func (t *SSEEventEnvelope) MergeSSEError(v SSEError) error {
	v.Type = "error"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t SSEEventEnvelope) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t SSEEventEnvelope) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "complete":
		return t.AsSSEComplete()
	case "error":
		return t.AsSSEError()
	case "failed":
		return t.AsSSEFailed()
	case "phase_progress":
		return t.AsSSEPhaseProgress()
	case "sim_finished":
		return t.AsSSESimFinished()
	case "sim_skipped":
		return t.AsSSESimSkipped()
	case "sim_started":
		return t.AsSSESimStarted()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t SSEEventEnvelope) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *SSEEventEnvelope) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// AuthLoginWithBody request with any body
	AuthLoginWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AuthLogin(ctx context.Context, body AuthLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AuthRegisterWithBody request with any body
	AuthRegisterWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AuthRegister(ctx context.Context, body AuthRegisterJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// HealthCheck request
	HealthCheck(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DiscoverFlashWithBody request with any body
	DiscoverFlashWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	DiscoverFlash(ctx context.Context, body DiscoverFlashJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DiscoverMultiWithBody request with any body
	DiscoverMultiWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	DiscoverMulti(ctx context.Context, body DiscoverMultiJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DiscoverOneClickWithBody request with any body
	DiscoverOneClickWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	DiscoverOneClick(ctx context.Context, body DiscoverOneClickJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DiscoverJobStatus request
	DiscoverJobStatus(ctx context.Context, jobId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DiscoverJobStream request
	DiscoverJobStream(ctx context.Context, jobId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// KnowledgeSearchWithBody request with any body
	KnowledgeSearchWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	KnowledgeSearch(ctx context.Context, body KnowledgeSearchJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) AuthLoginWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAuthLoginRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AuthLogin(ctx context.Context, body AuthLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAuthLoginRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AuthRegisterWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAuthRegisterRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AuthRegister(ctx context.Context, body AuthRegisterJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAuthRegisterRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) HealthCheck(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHealthCheckRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DiscoverFlashWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDiscoverFlashRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DiscoverFlash(ctx context.Context, body DiscoverFlashJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDiscoverFlashRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DiscoverMultiWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDiscoverMultiRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DiscoverMulti(ctx context.Context, body DiscoverMultiJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDiscoverMultiRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DiscoverOneClickWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDiscoverOneClickRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DiscoverOneClick(ctx context.Context, body DiscoverOneClickJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDiscoverOneClickRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DiscoverJobStatus(ctx context.Context, jobId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDiscoverJobStatusRequest(c.Server, jobId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DiscoverJobStream(ctx context.Context, jobId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDiscoverJobStreamRequest(c.Server, jobId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) KnowledgeSearchWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewKnowledgeSearchRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) KnowledgeSearch(ctx context.Context, body KnowledgeSearchJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewKnowledgeSearchRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewAuthLoginRequest calls the generic AuthLogin builder with application/json body
func NewAuthLoginRequest(server string, body AuthLoginJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAuthLoginRequestWithBody(server, "application/json", bodyReader)
}

// NewAuthLoginRequestWithBody generates requests for AuthLogin with any type of body
func NewAuthLoginRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/auth/login")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewAuthRegisterRequest calls the generic AuthRegister builder with application/json body
func NewAuthRegisterRequest(server string, body AuthRegisterJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAuthRegisterRequestWithBody(server, "application/json", bodyReader)
}

// NewAuthRegisterRequestWithBody generates requests for AuthRegister with any type of body
func NewAuthRegisterRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/auth/register")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewHealthCheckRequest generates requests for HealthCheck
func NewHealthCheckRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDiscoverFlashRequest calls the generic DiscoverFlash builder with application/json body
func NewDiscoverFlashRequest(server string, body DiscoverFlashJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewDiscoverFlashRequestWithBody(server, "application/json", bodyReader)
}

// NewDiscoverFlashRequestWithBody generates requests for DiscoverFlash with any type of body
func NewDiscoverFlashRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v8/discover/flash")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDiscoverMultiRequest calls the generic DiscoverMulti builder with application/json body
func NewDiscoverMultiRequest(server string, body DiscoverMultiJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewDiscoverMultiRequestWithBody(server, "application/json", bodyReader)
}

// NewDiscoverMultiRequestWithBody generates requests for DiscoverMulti with any type of body
func NewDiscoverMultiRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v8/discover/multi")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDiscoverOneClickRequest calls the generic DiscoverOneClick builder with application/json body
func NewDiscoverOneClickRequest(server string, body DiscoverOneClickJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewDiscoverOneClickRequestWithBody(server, "application/json", bodyReader)
}

// NewDiscoverOneClickRequestWithBody generates requests for DiscoverOneClick with any type of body
func NewDiscoverOneClickRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v8/discover/one-click")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDiscoverJobStatusRequest generates requests for DiscoverJobStatus
func NewDiscoverJobStatusRequest(server string, jobId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "job_id", jobId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v8/discover/status/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDiscoverJobStreamRequest generates requests for DiscoverJobStream
func NewDiscoverJobStreamRequest(server string, jobId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "job_id", jobId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v8/discover/stream/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewKnowledgeSearchRequest calls the generic KnowledgeSearch builder with application/json body
func NewKnowledgeSearchRequest(server string, body KnowledgeSearchJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewKnowledgeSearchRequestWithBody(server, "application/json", bodyReader)
}

// NewKnowledgeSearchRequestWithBody generates requests for KnowledgeSearch with any type of body
func NewKnowledgeSearchRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v8/knowledge/search")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// AuthLoginWithBodyWithResponse request with any body
	AuthLoginWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AuthLoginHTTPResponse, error)

	AuthLoginWithResponse(ctx context.Context, body AuthLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*AuthLoginHTTPResponse, error)

	// AuthRegisterWithBodyWithResponse request with any body
	AuthRegisterWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AuthRegisterHTTPResponse, error)

	AuthRegisterWithResponse(ctx context.Context, body AuthRegisterJSONRequestBody, reqEditors ...RequestEditorFn) (*AuthRegisterHTTPResponse, error)

	// HealthCheckWithResponse request
	HealthCheckWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthCheckHTTPResponse, error)

	// DiscoverFlashWithBodyWithResponse request with any body
	DiscoverFlashWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DiscoverFlashHTTPResponse, error)

	DiscoverFlashWithResponse(ctx context.Context, body DiscoverFlashJSONRequestBody, reqEditors ...RequestEditorFn) (*DiscoverFlashHTTPResponse, error)

	// DiscoverMultiWithBodyWithResponse request with any body
	DiscoverMultiWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DiscoverMultiHTTPResponse, error)

	DiscoverMultiWithResponse(ctx context.Context, body DiscoverMultiJSONRequestBody, reqEditors ...RequestEditorFn) (*DiscoverMultiHTTPResponse, error)

	// DiscoverOneClickWithBodyWithResponse request with any body
	DiscoverOneClickWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DiscoverOneClickHTTPResponse, error)

	DiscoverOneClickWithResponse(ctx context.Context, body DiscoverOneClickJSONRequestBody, reqEditors ...RequestEditorFn) (*DiscoverOneClickHTTPResponse, error)

	// DiscoverJobStatusWithResponse request
	DiscoverJobStatusWithResponse(ctx context.Context, jobId string, reqEditors ...RequestEditorFn) (*DiscoverJobStatusHTTPResponse, error)

	// DiscoverJobStreamWithResponse request
	DiscoverJobStreamWithResponse(ctx context.Context, jobId string, reqEditors ...RequestEditorFn) (*DiscoverJobStreamHTTPResponse, error)

	// KnowledgeSearchWithBodyWithResponse request with any body
	KnowledgeSearchWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*KnowledgeSearchHTTPResponse, error)

	KnowledgeSearchWithResponse(ctx context.Context, body KnowledgeSearchJSONRequestBody, reqEditors ...RequestEditorFn) (*KnowledgeSearchHTTPResponse, error)
}

type AuthLoginHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *LoginResponse
}

// Status returns HTTPResponse.Status
func (r AuthLoginHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AuthLoginHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r AuthLoginHTTPResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type AuthRegisterHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r AuthRegisterHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AuthRegisterHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r AuthRegisterHTTPResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type HealthCheckHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HealthResponse
}

// Status returns HTTPResponse.Status
func (r HealthCheckHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HealthCheckHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r HealthCheckHTTPResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DiscoverFlashHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *FlexibleObject
}

// Status returns HTTPResponse.Status
func (r DiscoverFlashHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DiscoverFlashHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DiscoverFlashHTTPResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DiscoverMultiHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *FlexibleObject
}

// Status returns HTTPResponse.Status
func (r DiscoverMultiHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DiscoverMultiHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DiscoverMultiHTTPResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DiscoverOneClickHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *JobCreatedResponse
}

// Status returns HTTPResponse.Status
func (r DiscoverOneClickHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DiscoverOneClickHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DiscoverOneClickHTTPResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DiscoverJobStatusHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *JobStatusResponse
}

// Status returns HTTPResponse.Status
func (r DiscoverJobStatusHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DiscoverJobStatusHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DiscoverJobStatusHTTPResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DiscoverJobStreamHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DiscoverJobStreamHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DiscoverJobStreamHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DiscoverJobStreamHTTPResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type KnowledgeSearchHTTPResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *KnowledgeSearchResponse
}

// Status returns HTTPResponse.Status
func (r KnowledgeSearchHTTPResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r KnowledgeSearchHTTPResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r KnowledgeSearchHTTPResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// AuthLoginWithBodyWithResponse request with arbitrary body returning *AuthLoginHTTPResponse
func (c *ClientWithResponses) AuthLoginWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AuthLoginHTTPResponse, error) {
	rsp, err := c.AuthLoginWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAuthLoginHTTPResponse(rsp)
}

func (c *ClientWithResponses) AuthLoginWithResponse(ctx context.Context, body AuthLoginJSONRequestBody, reqEditors ...RequestEditorFn) (*AuthLoginHTTPResponse, error) {
	rsp, err := c.AuthLogin(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAuthLoginHTTPResponse(rsp)
}

// AuthRegisterWithBodyWithResponse request with arbitrary body returning *AuthRegisterHTTPResponse
func (c *ClientWithResponses) AuthRegisterWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AuthRegisterHTTPResponse, error) {
	rsp, err := c.AuthRegisterWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAuthRegisterHTTPResponse(rsp)
}

func (c *ClientWithResponses) AuthRegisterWithResponse(ctx context.Context, body AuthRegisterJSONRequestBody, reqEditors ...RequestEditorFn) (*AuthRegisterHTTPResponse, error) {
	rsp, err := c.AuthRegister(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAuthRegisterHTTPResponse(rsp)
}

// HealthCheckWithResponse request returning *HealthCheckHTTPResponse
func (c *ClientWithResponses) HealthCheckWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthCheckHTTPResponse, error) {
	rsp, err := c.HealthCheck(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHealthCheckHTTPResponse(rsp)
}

// DiscoverFlashWithBodyWithResponse request with arbitrary body returning *DiscoverFlashHTTPResponse
func (c *ClientWithResponses) DiscoverFlashWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DiscoverFlashHTTPResponse, error) {
	rsp, err := c.DiscoverFlashWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDiscoverFlashHTTPResponse(rsp)
}

func (c *ClientWithResponses) DiscoverFlashWithResponse(ctx context.Context, body DiscoverFlashJSONRequestBody, reqEditors ...RequestEditorFn) (*DiscoverFlashHTTPResponse, error) {
	rsp, err := c.DiscoverFlash(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDiscoverFlashHTTPResponse(rsp)
}

// DiscoverMultiWithBodyWithResponse request with arbitrary body returning *DiscoverMultiHTTPResponse
func (c *ClientWithResponses) DiscoverMultiWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DiscoverMultiHTTPResponse, error) {
	rsp, err := c.DiscoverMultiWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDiscoverMultiHTTPResponse(rsp)
}

func (c *ClientWithResponses) DiscoverMultiWithResponse(ctx context.Context, body DiscoverMultiJSONRequestBody, reqEditors ...RequestEditorFn) (*DiscoverMultiHTTPResponse, error) {
	rsp, err := c.DiscoverMulti(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDiscoverMultiHTTPResponse(rsp)
}

// DiscoverOneClickWithBodyWithResponse request with arbitrary body returning *DiscoverOneClickHTTPResponse
func (c *ClientWithResponses) DiscoverOneClickWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DiscoverOneClickHTTPResponse, error) {
	rsp, err := c.DiscoverOneClickWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDiscoverOneClickHTTPResponse(rsp)
}

func (c *ClientWithResponses) DiscoverOneClickWithResponse(ctx context.Context, body DiscoverOneClickJSONRequestBody, reqEditors ...RequestEditorFn) (*DiscoverOneClickHTTPResponse, error) {
	rsp, err := c.DiscoverOneClick(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDiscoverOneClickHTTPResponse(rsp)
}

// DiscoverJobStatusWithResponse request returning *DiscoverJobStatusHTTPResponse
func (c *ClientWithResponses) DiscoverJobStatusWithResponse(ctx context.Context, jobId string, reqEditors ...RequestEditorFn) (*DiscoverJobStatusHTTPResponse, error) {
	rsp, err := c.DiscoverJobStatus(ctx, jobId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDiscoverJobStatusHTTPResponse(rsp)
}

// DiscoverJobStreamWithResponse request returning *DiscoverJobStreamHTTPResponse
func (c *ClientWithResponses) DiscoverJobStreamWithResponse(ctx context.Context, jobId string, reqEditors ...RequestEditorFn) (*DiscoverJobStreamHTTPResponse, error) {
	rsp, err := c.DiscoverJobStream(ctx, jobId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDiscoverJobStreamHTTPResponse(rsp)
}

// KnowledgeSearchWithBodyWithResponse request with arbitrary body returning *KnowledgeSearchHTTPResponse
func (c *ClientWithResponses) KnowledgeSearchWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*KnowledgeSearchHTTPResponse, error) {
	rsp, err := c.KnowledgeSearchWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseKnowledgeSearchHTTPResponse(rsp)
}

func (c *ClientWithResponses) KnowledgeSearchWithResponse(ctx context.Context, body KnowledgeSearchJSONRequestBody, reqEditors ...RequestEditorFn) (*KnowledgeSearchHTTPResponse, error) {
	rsp, err := c.KnowledgeSearch(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseKnowledgeSearchHTTPResponse(rsp)
}

// ParseAuthLoginHTTPResponse parses an HTTP response from a AuthLoginWithResponse call
func ParseAuthLoginHTTPResponse(rsp *http.Response) (*AuthLoginHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AuthLoginHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest LoginResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseAuthRegisterHTTPResponse parses an HTTP response from a AuthRegisterWithResponse call
func ParseAuthRegisterHTTPResponse(rsp *http.Response) (*AuthRegisterHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AuthRegisterHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseHealthCheckHTTPResponse parses an HTTP response from a HealthCheckWithResponse call
func ParseHealthCheckHTTPResponse(rsp *http.Response) (*HealthCheckHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HealthCheckHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseDiscoverFlashHTTPResponse parses an HTTP response from a DiscoverFlashWithResponse call
func ParseDiscoverFlashHTTPResponse(rsp *http.Response) (*DiscoverFlashHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DiscoverFlashHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest FlexibleObject
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseDiscoverMultiHTTPResponse parses an HTTP response from a DiscoverMultiWithResponse call
func ParseDiscoverMultiHTTPResponse(rsp *http.Response) (*DiscoverMultiHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DiscoverMultiHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest FlexibleObject
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseDiscoverOneClickHTTPResponse parses an HTTP response from a DiscoverOneClickWithResponse call
func ParseDiscoverOneClickHTTPResponse(rsp *http.Response) (*DiscoverOneClickHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DiscoverOneClickHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest JobCreatedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseDiscoverJobStatusHTTPResponse parses an HTTP response from a DiscoverJobStatusWithResponse call
func ParseDiscoverJobStatusHTTPResponse(rsp *http.Response) (*DiscoverJobStatusHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DiscoverJobStatusHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest JobStatusResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseDiscoverJobStreamHTTPResponse parses an HTTP response from a DiscoverJobStreamWithResponse call
func ParseDiscoverJobStreamHTTPResponse(rsp *http.Response) (*DiscoverJobStreamHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DiscoverJobStreamHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseKnowledgeSearchHTTPResponse parses an HTTP response from a KnowledgeSearchWithResponse call
func ParseKnowledgeSearchHTTPResponse(rsp *http.Response) (*KnowledgeSearchHTTPResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &KnowledgeSearchHTTPResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest KnowledgeSearchResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
